// Package apitypes writes TypeScript declarations of the API's JSON
// responses from the Go structs that the handlers encode, so the console's
// types follow the backend instead of a copy kept by hand.
//
// Generate declares each registered struct as an object type whose
// properties are the struct's JSON fields, as encoding/json writes them. A
// field that omitempty or omitzero can leave out is optional, and a pointer,
// slice, or map that encoding/json writes as null when it is nil admits null
// unless the field leaves it out instead. A field of a named struct type
// refers to that struct's declaration, so every named struct that a
// registered struct contains must be registered too; an anonymous struct is
// declared inline.
package apitypes

import (
	"encoding"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"time"
)

// Header starts the generated file.
const Header = `// Code generated by go run ./scripts/gen-api-types; DO NOT EDIT.
//
// To change these declarations, change the Go structs that
// internal/web/api_types.go lists and run the command again from the
// repository root.`

// Type is a Go struct that Generate declares under its TypeScript name.
type Type struct {
	// Name is the name of the TypeScript declaration.
	Name string
	// Value is a value of the struct, such as model.Scan{}.
	Value any
}

var (
	identifier        = regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`)
	timeType          = reflect.TypeFor[time.Time]()
	marshalerType     = reflect.TypeFor[json.Marshaler]()
	textMarshalerType = reflect.TypeFor[encoding.TextMarshaler]()
)

// field is one JSON field of a struct.
type field struct {
	name     string
	optional bool
	typ      reflect.Type
}

// generator names the registered structs.
type generator struct {
	names map[reflect.Type]string
}

// Generate returns the TypeScript declarations of the types, in their order,
// after Header. It fails when a type is not a named struct, when two types
// share a name or a struct, when a field has no JSON name or encodes in a way
// that its Go type does not describe, and when a registered struct contains
// a named struct that is not registered.
func Generate(types []Type) ([]byte, error) {
	g := generator{names: make(map[reflect.Type]string, len(types))}
	declared := make(map[string]bool, len(types))
	for _, registered := range types {
		t := reflect.TypeOf(registered.Value)
		if t == nil || t.Kind() != reflect.Struct || t.Name() == "" {
			return nil, fmt.Errorf("%s: %v is not a named struct", registered.Name, t)
		}
		if !identifier.MatchString(registered.Name) {
			return nil, fmt.Errorf("%s: %q is not a TypeScript name", t, registered.Name)
		}
		if declared[registered.Name] {
			return nil, fmt.Errorf("%s: the name %s is registered twice", t, registered.Name)
		}
		if previous, ok := g.names[t]; ok {
			return nil, fmt.Errorf("%s: registered as %s and %s", t, previous, registered.Name)
		}
		declared[registered.Name] = true
		g.names[t] = registered.Name
	}
	var out strings.Builder
	out.WriteString(Header + "\n")
	for _, registered := range types {
		t := reflect.TypeOf(registered.Value)
		body, err := g.object(t, true)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", registered.Name, err)
		}
		fmt.Fprintf(&out, "\n// %s is %s.\nexport type %s = %s\n", registered.Name, t, registered.Name, body)
	}
	return []byte(out.String()), nil
}

// CheckTags reports every exported field of the types, and of the anonymous
// structs that they contain, that has no json tag or whose tag names no
// field. It reports all of them at once.
func CheckTags(types []Type) error {
	var problems []error
	for _, registered := range types {
		t := reflect.TypeOf(registered.Value)
		if t == nil || t.Kind() != reflect.Struct {
			problems = append(problems, fmt.Errorf("%s: %v is not a struct", registered.Name, t))
			continue
		}
		problems = append(problems, checkStruct(t, t.String())...)
	}
	return errors.Join(problems...)
}

func checkStruct(t reflect.Type, path string) []error {
	var problems []error
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() && !f.Anonymous {
			continue
		}
		if _, err := jsonField(f); err != nil {
			problems = append(problems, fmt.Errorf("%s.%s: %w", path, f.Name, err))
		}
		if inner := elementOf(f.Type); inner.Kind() == reflect.Struct && inner.Name() == "" {
			problems = append(problems, checkStruct(inner, path+"."+f.Name)...)
		}
	}
	return problems
}

// elementOf returns the type that the pointers, slices, arrays, and maps of
// t hold.
func elementOf(t reflect.Type) reflect.Type {
	for {
		switch t.Kind() {
		case reflect.Pointer, reflect.Slice, reflect.Array, reflect.Map:
			t = t.Elem()
		default:
			return t
		}
	}
}

// jsonField returns how encoding/json writes the exported field f, or nil
// when it leaves the field out with the tag "-".
func jsonField(f reflect.StructField) (*field, error) {
	if f.Anonymous {
		return nil, errors.New("embedded fields are not supported; name the field and give it a json tag")
	}
	tag, ok := f.Tag.Lookup("json")
	if !ok {
		return nil, errors.New("has no json tag")
	}
	if tag == "-" {
		return nil, nil
	}
	name, options, _ := strings.Cut(tag, ",")
	if name == "" {
		return nil, fmt.Errorf("json tag %q names no field", tag)
	}
	result := &field{name: name, typ: f.Type}
	for option := range strings.SplitSeq(options, ",") {
		switch option {
		case "omitzero":
			result.optional = true
		case "omitempty":
			result.optional = result.optional || omitsEmpty(f.Type)
		case "string":
			return nil, fmt.Errorf("json tag %q: the string option is not supported", tag)
		}
	}
	return result, nil
}

// omitsEmpty reports whether omitempty can leave out a value of type t:
// encoding/json never leaves out a struct or a non-empty array.
func omitsEmpty(t reflect.Type) bool {
	switch t.Kind() {
	case reflect.Struct:
		return false
	case reflect.Array:
		return t.Len() == 0
	default:
		return true
	}
}

// fields returns the JSON fields of the struct t, in its order.
func fields(t reflect.Type) ([]field, error) {
	var result []field
	seen := map[string]bool{}
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() && !f.Anonymous {
			continue
		}
		described, err := jsonField(f)
		if err != nil {
			return nil, fmt.Errorf("%s.%s: %w", t, f.Name, err)
		}
		if described == nil {
			continue
		}
		if seen[described.name] {
			return nil, fmt.Errorf("%s.%s: the JSON field %s is declared twice", t, f.Name, described.name)
		}
		seen[described.name] = true
		result = append(result, *described)
	}
	return result, nil
}

// object returns the TypeScript object type of the struct t, one property
// per line when multiline is set.
func (g generator) object(t reflect.Type, multiline bool) (string, error) {
	described, err := fields(t)
	if err != nil {
		return "", err
	}
	if len(described) == 0 {
		return "Record<string, never>", nil
	}
	properties := make([]string, 0, len(described))
	for _, f := range described {
		value, err := g.value(f.typ)
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", t, f.name, err)
		}
		name := f.name
		if !identifier.MatchString(name) {
			name = strconv.Quote(name)
		}
		if f.optional {
			// A field that is left out when it is nil is never null.
			value = strings.TrimSuffix(value, " | null")
			name += "?"
		}
		properties = append(properties, name+": "+value)
	}
	if multiline {
		return "{\n  " + strings.Join(properties, "\n  ") + "\n}", nil
	}
	return "{ " + strings.Join(properties, "; ") + " }", nil
}

// value returns the TypeScript type of the JSON that encoding/json writes for
// a value of type t.
func (g generator) value(t reflect.Type) (string, error) {
	if t.Kind() == reflect.Pointer {
		element, err := g.value(t.Elem())
		if err != nil {
			return "", err
		}
		return nullable(element), nil
	}
	if t == timeType {
		return "string", nil
	}
	if encodesItself(t) {
		return "", fmt.Errorf("%v encodes itself, so its Go type does not describe its JSON", t)
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.String:
		return "string", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.Interface:
		return "unknown", nil
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			// encoding/json writes a byte slice as base64.
			return "string | null", nil
		}
		element, err := g.value(t.Elem())
		if err != nil {
			return "", err
		}
		return nullable(array(element)), nil
	case reflect.Array:
		element, err := g.value(t.Elem())
		if err != nil {
			return "", err
		}
		return array(element), nil
	case reflect.Map:
		switch t.Key().Kind() {
		case reflect.String, reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		default:
			return "", fmt.Errorf("map key %v is not supported", t.Key())
		}
		element, err := g.value(t.Elem())
		if err != nil {
			return "", err
		}
		return nullable("Record<string, " + element + ">"), nil
	case reflect.Struct:
		if name, ok := g.names[t]; ok {
			return name, nil
		}
		if t.Name() != "" {
			return "", fmt.Errorf("%v is not registered", t)
		}
		return g.object(t, false)
	default:
		return "", fmt.Errorf("%v cannot be encoded as JSON", t)
	}
}

// encodesItself reports whether encoding/json writes a value of type t with
// its own MarshalJSON or MarshalText method.
func encodesItself(t reflect.Type) bool {
	pointer := reflect.PointerTo(t)
	return t.Implements(marshalerType) || pointer.Implements(marshalerType) || t.Implements(textMarshalerType) || pointer.Implements(textMarshalerType)
}

// nullable adds null to the type, once.
func nullable(value string) string {
	if strings.HasSuffix(value, " | null") || value == "unknown" {
		return value
	}
	return value + " | null"
}

// array returns the array type of the element type. The only unions that
// value returns end in null.
func array(element string) string {
	if strings.HasSuffix(element, " | null") {
		return "(" + element + ")[]"
	}
	return element + "[]"
}
