import { FormEvent, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useQueryClient } from '@tanstack/react-query'
import { Eye, EyeOff, LockKeyhole, Wifi } from 'lucide-react'
import { login, setCSRF, setup } from '../api'

export function Login() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [password, setPassword] = useState(''); const [otp, setOtp] = useState(''); const [recovery, setRecovery] = useState(''); const [showRecovery, setShowRecovery] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setBusy(true); try { const value = await login(password, otp, showRecovery ? recovery : undefined); setCSRF(value.csrf_token); await queryClient.invalidateQueries({ queryKey: ['session'] }); await queryClient.invalidateQueries({ queryKey: ['setup-status'] }); navigate('/') } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sign in') } finally { setBusy(false) } }
  return <AuthFrame eyebrow="Welcome back" title="Sign in to EdgeWatch" subtitle="Review your network surface and respond to changes."><form onSubmit={submit} className="auth-form"><label>Password<input autoFocus type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" required /></label><label>{showRecovery ? 'Recovery code' : 'Authenticator code'}<input inputMode={showRecovery ? 'text' : 'numeric'} value={showRecovery ? recovery : otp} onChange={e => showRecovery ? setRecovery(e.target.value) : setOtp(e.target.value)} placeholder={showRecovery ? 'AB12CD34EF' : '123456'} autoComplete="one-time-code" /></label>{error && <div className="form-error">{error}</div>}<button disabled={busy} className="button primary wide" type="submit">{busy ? 'Signing in…' : 'Sign in'}</button><button type="button" className="link-button" onClick={() => setShowRecovery(v => !v)}>{showRecovery ? 'Use authenticator code' : 'Use a recovery code'}</button></form></AuthFrame>
}

export function Setup() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [token, setToken] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); if (password.length < 12) { setError('Use at least 12 characters for the administrator password.'); return } if (password !== confirm) { setError('Passwords do not match.'); return }; setBusy(true); try { await setup(token.trim(), password); await queryClient.invalidateQueries({ queryKey: ['setup-status'] }); await queryClient.invalidateQueries({ queryKey: ['session'] }); navigate('/login') } catch (err) { setError(err instanceof Error ? err.message : 'Setup failed') } finally { setBusy(false) } }
  return <AuthFrame eyebrow="First-run setup" title="Create your administrator" subtitle="The setup token is printed once in the EdgeWatch container logs and expires after 15 minutes."><form onSubmit={submit} className="auth-form"><label>Setup token<input autoFocus value={token} onChange={e => setToken(e.target.value)} autoComplete="one-time-code" placeholder="Paste the token from the logs" required /></label><label>Password<div className="input-with-action"><input type={show ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" minLength={12} required /><button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={() => setShow(v => !v)}>{show ? <EyeOff size={17} /> : <Eye size={17} />}</button></div><small>At least 12 characters. You can enable TOTP after signing in.</small></label><label>Confirm password<input type="password" value={confirm} onChange={e => setConfirm(e.target.value)} autoComplete="new-password" required /></label>{error && <div className="form-error">{error}</div>}<button disabled={busy} className="button primary wide" type="submit">{busy ? 'Creating account…' : 'Create administrator'}</button></form></AuthFrame>
}

function AuthFrame({ eyebrow, title, subtitle, children }: { eyebrow: string; title: string; subtitle: string; children: React.ReactNode }) { return <div className="auth-layout"><div className="auth-art"><div className="brand light"><span className="brand-mark"><Wifi size={19} /></span><span>EdgeWatch</span></div><div className="art-copy"><div className="signal"><i /><i /><i /><i /><i /></div><h2>Know what changed.</h2><p>Simple, scheduled network visibility for the systems you own.</p></div><span className="art-footer">Local-first · Privacy-minded · Built for operators</span></div><div className="auth-side"><div className="auth-card"><div className="auth-mobile-brand"><Wifi size={18} /> EdgeWatch</div><div className="auth-heading"><div className="auth-icon"><LockKeyhole size={20} /></div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{subtitle}</p></div>{children}</div></div></div> }
