package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"sort"
	"strings"
	"time"

	"github.com/crypt0rr/edgewatch/internal/config"
	"github.com/crypt0rr/edgewatch/internal/model"
	"github.com/crypt0rr/edgewatch/internal/scanner"
	"github.com/google/uuid"
)

var (
	ErrNoScanCycle       = errors.New("scan cycle not found")
	ErrNoPendingUnit     = errors.New("scan cycle has no pending work")
	ErrCycleNotResumable = errors.New("scan cycle is not resumable")
	ErrCycleIncomplete   = errors.New("scan cycle is incomplete")
)

// scanCycleReconcileBatchSize bounds the amount of discovery evidence and
// dynamic work generated by one writer transaction. A full-range Naabu cycle
// can contain thousands of address batches; processing them in bounded
// chunks keeps the writer available to foreground scan/checkpoint writes.
const scanCycleReconcileBatchSize = 64

// ScanCycleRecord is the durable state for a complete scope scan that may
// require more than one attempt. The plan includes the normalized job and
// pinned DNS expansion so a resumed cycle never silently changes scope.
type ScanCycleRecord struct {
	ID                 string
	JobID              string
	Job                string
	JobRevision        int64
	ConfigHash         string
	ExecutionHash      string
	Plan               scanner.WorkPlan
	Status             string
	AttemptCount       int
	NoProgressAttempts int
	TotalUnits         int
	CompletedUnits     int
	TotalProbes        int64
	CompletedProbes    int64
	StartedAt          time.Time
	UpdatedAt          time.Time
	ExpiresAt          time.Time
	FinishedAt         time.Time
	LastError          string
}

// ScanCycleUnit is one independently persisted Nmap invocation.
type ScanCycleUnit struct {
	CycleID    string
	Sequence   int
	Unit       scanner.WorkUnit
	Status     string
	Attempts   int
	Snapshot   model.Snapshot
	StartedAt  time.Time
	FinishedAt time.Time
	LastError  string
}

// ScanCycleUnitSummary is the safe progress view returned to the web console.
// It omits checkpoint payloads, which can be very large for a full-range job.
type ScanCycleUnitSummary struct {
	CycleID    string    `json:"cycle_id"`
	Sequence   int       `json:"sequence"`
	Engine     string    `json:"engine,omitempty"`
	Phase      string    `json:"phase,omitempty"`
	Protocol   string    `json:"protocol"`
	Family     int       `json:"family"`
	Ports      string    `json:"ports"`
	PortCount  int       `json:"port_count"`
	Addresses  int       `json:"addresses"`
	Probes     int64     `json:"probes"`
	Status     string    `json:"status"`
	Attempts   int       `json:"attempts"`
	StartedAt  time.Time `json:"started_at"`
	FinishedAt time.Time `json:"finished_at"`
	LastError  string    `json:"last_error,omitempty"`
}

func (s *Store) CreateScanCycle(ctx context.Context, cycle ScanCycleRecord) (ScanCycleRecord, error) {
	if cycle.JobID == "" || cycle.Job == "" {
		return ScanCycleRecord{}, errors.New("scan cycle job is required")
	}
	if len(cycle.Plan.Units) == 0 {
		return ScanCycleRecord{}, errors.New("scan cycle has no work units")
	}
	if cycle.ID == "" {
		cycle.ID = uuid.NewString()
	}
	now := cycle.StartedAt.UTC()
	if now.IsZero() {
		now = time.Now().UTC()
	}
	cycle.StartedAt = now
	if cycle.UpdatedAt.IsZero() {
		cycle.UpdatedAt = now
	}
	if cycle.ExpiresAt.IsZero() {
		cycle.ExpiresAt = now.Add(8 * 24 * time.Hour)
	}
	cycle.Status = "paused"
	cycle.TotalUnits = len(cycle.Plan.Units)
	// Treat the persisted unit list as the source of truth for progress. This
	// also keeps alternate scanners safe when they omit the aggregate totals in
	// their plan; a resumed cycle must never advertise zero work for non-empty
	// units or over-count probes after a split.
	var plannedProbes int64
	for _, unit := range cycle.Plan.Units {
		plannedProbes += unit.Probes
	}
	cycle.TotalProbes = plannedProbes
	cycle.Plan.TotalUnits = cycle.TotalUnits
	cycle.Plan.TotalProbes = plannedProbes
	planJSON, err := json.Marshal(cycle.Plan)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	defer tx.Rollback()
	_, err = tx.ExecContext(ctx, `INSERT INTO scan_cycles(id,job_id,job,job_revision,config_hash,execution_hash,plan_json,status,attempt_count,no_progress_attempts,total_units,completed_units,total_probes,completed_probes,started_at,updated_at,expires_at,finished_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
		cycle.ID, cycle.JobID, cycle.Job, cycle.JobRevision, cycle.ConfigHash, cycle.ExecutionHash, planJSON, cycle.Status, cycle.AttemptCount, cycle.NoProgressAttempts, cycle.TotalUnits, cycle.CompletedUnits, cycle.TotalProbes, cycle.CompletedProbes, cycle.StartedAt.Format(time.RFC3339Nano), cycle.UpdatedAt.Format(time.RFC3339Nano), cycle.ExpiresAt.Format(time.RFC3339Nano), "", cycle.LastError)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	for _, unit := range cycle.Plan.Units {
		raw, marshalErr := json.Marshal(unit)
		if marshalErr != nil {
			return ScanCycleRecord{}, marshalErr
		}
		if _, err = tx.ExecContext(ctx, `INSERT INTO scan_cycle_units(cycle_id,sequence,work_unit_json,identity,status,attempts,snapshot_json,started_at,finished_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?)`, cycle.ID, unit.Sequence, raw, scanCycleUnitIdentity(unit), "pending", 0, []byte(`{}`), "", "", ""); err != nil {
			return ScanCycleRecord{}, err
		}
	}
	if err = tx.Commit(); err != nil {
		return ScanCycleRecord{}, err
	}
	return cycle, nil
}

// ReconcileScanCycleEnrichment expands a phase-aware Naabu cycle from durable
// discovery checkpoints. Each bounded batch marks its discovery rows in the
// same transaction that creates the corresponding Nmap enrichment work. The
// method drains all available batches, but every transaction is capped by
// scanCycleReconcileBatchSize and can be interrupted by the caller's context.
//
// Dynamic units are authoritative in scan_cycle_units. We deliberately do not
// rewrite the potentially very large plan_json blob for every discovery batch;
// this keeps reconciliation linear in the amount of newly completed evidence.
// GetScanCycle reports the authoritative counters from scan_cycles, while
// LoadScanCycleFragments uses the unit table when promoting a completed cycle.
func (s *Store) ReconcileScanCycleEnrichment(ctx context.Context, cycleID string) error {
	cycle, err := s.GetScanCycle(ctx, cycleID)
	if err != nil {
		return err
	}
	if cycle.Status != "running" && cycle.Status != "paused" && cycle.Status != "stalled" {
		return nil
	}
	if cycle.Plan.Job.TCP == nil || cycle.Plan.Job.TCP.Engine != config.EngineNaabuNmap {
		return nil
	}

	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		worked, batchErr := s.reconcileScanCycleEnrichmentBatch(ctx, cycleID, cycle.Plan)
		if batchErr != nil {
			return batchErr
		}
		if !worked {
			return nil
		}
	}
}

// reconcileScanCycleEnrichmentBatch performs one bounded reconciliation
// transaction. The bool reports whether more checkpoint or dynamic work was
// committed and lets the caller drain additional batches without making the
// writer transaction itself unbounded.
func (s *Store) reconcileScanCycleEnrichmentBatch(ctx context.Context, cycleID string, plan scanner.WorkPlan) (bool, error) {
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return false, err
	}
	defer tx.Rollback()
	var status string
	if err := tx.QueryRowContext(ctx, `SELECT status FROM scan_cycles WHERE id=?`, cycleID).Scan(&status); errors.Is(err, sql.ErrNoRows) {
		return false, fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
	} else if err != nil {
		return false, err
	}
	if status != "running" && status != "paused" && status != "stalled" {
		return false, tx.Commit()
	}

	// JSON1 lets SQLite count phase rows without loading every checkpoint
	// payload. The table is indexed by cycle and sequence, and only the first
	// bounded batch is decoded below.
	var discoveryCount, completedDiscoveryCount int
	if err := tx.QueryRowContext(ctx, `SELECT COUNT(*),COALESCE(SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END),0) FROM scan_cycle_units WHERE cycle_id=? AND json_extract(work_unit_json,'$.phase')='discovery'`, cycleID).Scan(&discoveryCount, &completedDiscoveryCount); err != nil {
		return false, err
	}
	if discoveryCount == 0 {
		return false, tx.Commit()
	}
	discoveryComplete := completedDiscoveryCount == discoveryCount

	type discoveryRow struct {
		sequence int
		unit     scanner.WorkUnit
		snapshot model.Snapshot
	}
	rows, err := tx.QueryContext(ctx, `SELECT u.sequence,u.work_unit_json,u.snapshot_json FROM scan_cycle_units AS u WHERE u.cycle_id=? AND u.status='completed' AND json_extract(u.work_unit_json,'$.phase')='discovery' AND NOT EXISTS (SELECT 1 FROM scan_cycle_discovery_checkpoints AS c WHERE c.cycle_id=u.cycle_id AND c.sequence=u.sequence) ORDER BY u.sequence LIMIT ?`, cycleID, scanCycleReconcileBatchSize)
	if err != nil {
		return false, err
	}
	var pending []discoveryRow
	for rows.Next() {
		var row discoveryRow
		var unitRaw, snapshotRaw []byte
		if err := rows.Scan(&row.sequence, &unitRaw, &snapshotRaw); err != nil {
			rows.Close()
			return false, err
		}
		if err := json.Unmarshal(unitRaw, &row.unit); err != nil {
			rows.Close()
			return false, err
		}
		if len(snapshotRaw) > 0 && string(snapshotRaw) != "{}" && string(snapshotRaw) != "null" {
			if err := json.Unmarshal(snapshotRaw, &row.snapshot); err != nil {
				rows.Close()
				return false, err
			}
		}
		pending = append(pending, row)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return false, err
	}
	rows.Close()

	// Gather one deterministic port set per effective address from only this
	// batch. Discovery address batches are disjoint; unioning within the batch
	// still protects against duplicate host observations during recovery.
	portsByAddress := map[string]map[int]struct{}{}
	for _, row := range pending {
		for _, host := range row.snapshot.Hosts {
			address := normalizeCycleAddress(host.Address)
			if address == "" {
				continue
			}
			for _, protocol := range host.Protocols {
				if protocol.Protocol != "tcp" || protocol.DiscoveryEngine != "naabu" {
					continue
				}
				set := portsByAddress[address]
				if set == nil {
					set = map[int]struct{}{}
					portsByAddress[address] = set
				}
				for _, port := range protocol.DiscoveredPorts {
					if port.Port >= 1 && port.Port <= 65535 {
						set[port.Port] = struct{}{}
					}
				}
			}
		}
	}

	type discoveryGroup struct {
		family    int
		ports     []int
		addresses []string
	}
	groups := map[string]*discoveryGroup{}
	for address, set := range portsByAddress {
		if len(set) == 0 {
			continue
		}
		ports := make([]int, 0, len(set))
		for port := range set {
			ports = append(ports, port)
		}
		sort.Ints(ports)
		family := 4
		if ip := net.ParseIP(address); ip != nil && ip.To4() == nil {
			family = 6
		}
		key := fmt.Sprintf("%d\x00%s", family, formatCyclePorts(ports))
		group := groups[key]
		if group == nil {
			group = &discoveryGroup{family: family, ports: ports}
			groups[key] = group
		}
		group.addresses = append(group.addresses, address)
	}
	groupKeys := make([]string, 0, len(groups))
	for key := range groups {
		groupKeys = append(groupKeys, key)
	}
	sort.Strings(groupKeys)

	var nextSequence int
	if err := tx.QueryRowContext(ctx, `SELECT COALESCE(MAX(sequence),-1)+1 FROM scan_cycle_units WHERE cycle_id=?`, cycleID).Scan(&nextSequence); err != nil {
		return false, err
	}
	var added []scanner.WorkUnit
	newIdentities := make(map[string]struct{})
	factor := boolFactor(plan.Job.TCP.ServiceDetection)
	addressBatchSize := scanner.NmapAddressBatchLimit(plan.Job.TCP.EnrichmentArgs)
	for _, key := range groupKeys {
		group := groups[key]
		sort.Strings(group.addresses)
		for addressStart := 0; addressStart < len(group.addresses); addressStart += addressBatchSize {
			addressEnd := addressStart + addressBatchSize
			if addressEnd > len(group.addresses) {
				addressEnd = len(group.addresses)
			}
			addresses := append([]string(nil), group.addresses[addressStart:addressEnd]...)
			perChunk := scanner.MaxWorkUnitPorts
			if capacity := int(scanner.MaxWorkUnitProbes / (int64(len(addresses)) * factor)); capacity > 0 && perChunk > capacity {
				perChunk = capacity
			}
			if perChunk < 1 {
				perChunk = 1
			}
			for portStart := 0; portStart < len(group.ports); portStart += perChunk {
				portEnd := portStart + perChunk
				if portEnd > len(group.ports) {
					portEnd = len(group.ports)
				}
				portChunk := group.ports[portStart:portEnd]
				unit := scanner.WorkUnit{Sequence: nextSequence, Engine: config.EngineNmap, Phase: "enrichment", Protocol: "tcp", Family: group.family, Targets: subsetCycleTargets(plan.Targets, addresses), Addresses: addresses, Ports: formatCyclePorts(portChunk), PortCount: len(portChunk), Probes: int64(len(addresses)) * int64(len(portChunk)) * factor}
				nextSequence++
				identity := scanCycleUnitIdentity(unit)
				if _, exists := newIdentities[identity]; exists {
					continue
				}
				exists, err := scanCycleUnitIdentityExists(ctx, tx, cycleID, identity)
				if err != nil {
					return false, err
				}
				if exists {
					continue
				}
				added = append(added, unit)
				newIdentities[identity] = struct{}{}
			}
		}
	}

	// Only append UDP after the final discovery batch has been checkpointed.
	// Otherwise a large recovery batch could place UDP ahead of enrichment work
	// belonging to later discovery rows.
	morePending := false
	if len(pending) > 0 {
		lastSequence := pending[len(pending)-1].sequence
		if err := tx.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM scan_cycle_units AS u WHERE u.cycle_id=? AND u.status='completed' AND json_extract(u.work_unit_json,'$.phase')='discovery' AND u.sequence>? AND NOT EXISTS (SELECT 1 FROM scan_cycle_discovery_checkpoints AS c WHERE c.cycle_id=u.cycle_id AND c.sequence=u.sequence))`, cycleID, lastSequence).Scan(&morePending); err != nil {
			return false, err
		}
	}
	if discoveryComplete && !morePending && plan.Job.UDP != nil {
		var udpCount int
		if err := tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM scan_cycle_units WHERE cycle_id=? AND json_extract(work_unit_json,'$.phase')='udp'`, cycleID).Scan(&udpCount); err != nil {
			return false, err
		}
		if udpCount == 0 {
			for _, unit := range buildCycleUDPUnits(plan, nextSequence) {
				identity := scanCycleUnitIdentity(unit)
				if _, exists := newIdentities[identity]; exists {
					continue
				}
				exists, err := scanCycleUnitIdentityExists(ctx, tx, cycleID, identity)
				if err != nil {
					return false, err
				}
				if exists {
					continue
				}
				added = append(added, unit)
				newIdentities[identity] = struct{}{}
			}
		}
	}

	stamp := time.Now().UTC().Format(time.RFC3339Nano)
	for _, row := range pending {
		if _, err := tx.ExecContext(ctx, `INSERT OR IGNORE INTO scan_cycle_discovery_checkpoints(cycle_id,sequence,processed_at) VALUES(?,?,?)`, cycleID, row.sequence, stamp); err != nil {
			return false, err
		}
	}
	var addedProbes int64
	for _, unit := range added {
		raw, err := json.Marshal(unit)
		if err != nil {
			return false, err
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO scan_cycle_units(cycle_id,sequence,work_unit_json,identity,status,attempts,snapshot_json,started_at,finished_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?)`, cycleID, unit.Sequence, raw, scanCycleUnitIdentity(unit), "pending", 0, []byte(`{}`), "", "", ""); err != nil {
			return false, err
		}
		addedProbes += unit.Probes
	}
	if len(added) > 0 {
		result, err := tx.ExecContext(ctx, `UPDATE scan_cycles SET total_units=total_units+?,total_probes=total_probes+?,updated_at=? WHERE id=? AND status IN ('running','paused','stalled')`, len(added), addedProbes, stamp, cycleID)
		if err != nil {
			return false, err
		}
		if count, _ := result.RowsAffected(); count != 1 {
			return false, ErrCycleNotResumable
		}
	}
	worked := len(pending) > 0 || len(added) > 0
	if err := tx.Commit(); err != nil {
		return false, err
	}
	return worked, nil
}

func scanCycleUnitIdentity(unit scanner.WorkUnit) string {
	addresses := append([]string(nil), unit.Addresses...)
	sort.Strings(addresses)
	return unit.Engine + "\x00" + unit.Phase + "\x00" + unit.Protocol + "\x00" + fmt.Sprint(unit.Family) + "\x00" + unit.Ports + "\x00" + strings.Join(addresses, ",")
}

func scanCycleUnitIdentityExists(ctx context.Context, tx *sql.Tx, cycleID, identity string) (bool, error) {
	var exists int
	err := tx.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM scan_cycle_units WHERE cycle_id=? AND identity=?)`, cycleID, identity).Scan(&exists)
	return exists != 0, err
}

func normalizeCycleAddress(raw string) string {
	if ip := net.ParseIP(strings.TrimSpace(raw)); ip != nil {
		return ip.String()
	}
	return ""
}

func formatCyclePorts(ports []int) string {
	if len(ports) == 0 {
		return ""
	}
	sort.Ints(ports)
	parts := make([]string, 0, len(ports))
	start, previous := ports[0], ports[0]
	flush := func() {
		if start == previous {
			parts = append(parts, fmt.Sprint(start))
		} else {
			parts = append(parts, fmt.Sprintf("%d-%d", start, previous))
		}
	}
	for _, port := range ports[1:] {
		if port == previous+1 {
			previous = port
			continue
		}
		flush()
		start, previous = port, port
	}
	flush()
	return strings.Join(parts, ",")
}

func boolFactor(serviceDetection bool) int64 {
	if serviceDetection {
		return 2
	}
	return 1
}

func subsetCycleTargets(targets []scanner.ResolvedTarget, addresses []string) []scanner.ResolvedTarget {
	set := make(map[string]struct{}, len(addresses))
	for _, address := range addresses {
		if normalized := normalizeCycleAddress(address); normalized != "" {
			set[normalized] = struct{}{}
		}
	}
	var out []scanner.ResolvedTarget
	for _, target := range targets {
		selected := make([]string, 0, len(target.Addresses))
		for _, address := range target.Addresses {
			if normalized := normalizeCycleAddress(address); normalized != "" {
				if _, ok := set[normalized]; ok {
					selected = append(selected, normalized)
				}
			}
		}
		if len(selected) == 0 {
			continue
		}
		sort.Strings(selected)
		out = append(out, scanner.ResolvedTarget{Name: target.Name, ConfiguredTarget: target.ConfiguredTarget, Addresses: selected, Aggregate: target.Aggregate, Hostname: target.Hostname})
	}
	return out
}

func buildCycleUDPUnits(plan scanner.WorkPlan, sequence int) []scanner.WorkUnit {
	if plan.Job.UDP == nil {
		return nil
	}
	ports, err := config.ParsePorts(plan.Job.UDP.Ports)
	if err != nil || len(ports) == 0 {
		return nil
	}
	byFamily := map[int][]string{4: {}, 6: {}}
	seen := map[string]struct{}{}
	for _, target := range plan.Targets {
		for _, raw := range target.Addresses {
			address := normalizeCycleAddress(raw)
			if address == "" {
				continue
			}
			if _, exists := seen[address]; exists {
				continue
			}
			seen[address] = struct{}{}
			family := 4
			if net.ParseIP(address).To4() == nil {
				family = 6
			}
			byFamily[family] = append(byFamily[family], address)
		}
	}
	var out []scanner.WorkUnit
	for _, family := range []int{4, 6} {
		addresses := byFamily[family]
		sort.Strings(addresses)
		for start := 0; start < len(addresses); start += 128 {
			end := start + 128
			if end > len(addresses) {
				end = len(addresses)
			}
			batch := append([]string(nil), addresses[start:end]...)
			factor := boolFactor(plan.Job.UDP.ServiceDetection)
			perChunk := 4096
			if capacity := int(65536 / (int64(len(batch)) * factor)); capacity > 0 && perChunk > capacity {
				perChunk = capacity
			}
			if perChunk < 1 {
				perChunk = 1
			}
			for portStart := 0; portStart < len(ports); portStart += perChunk {
				portEnd := portStart + perChunk
				if portEnd > len(ports) {
					portEnd = len(ports)
				}
				chunk := append([]int(nil), ports[portStart:portEnd]...)
				out = append(out, scanner.WorkUnit{Sequence: sequence, Engine: config.EngineNmap, Phase: "udp", Protocol: "udp", Family: family, Targets: subsetCycleTargets(plan.Targets, batch), Addresses: batch, Ports: formatCyclePorts(chunk), PortCount: len(chunk), Probes: int64(len(batch)) * int64(len(chunk)) * factor})
				sequence++
			}
		}
	}
	return out
}

func (s *Store) GetScanCycle(ctx context.Context, id string) (ScanCycleRecord, error) {
	var cycle ScanCycleRecord
	var planJSON []byte
	var started, updated, expires, finished string
	err := s.reader().QueryRowContext(ctx, `SELECT id,job_id,job,job_revision,config_hash,execution_hash,plan_json,status,attempt_count,no_progress_attempts,total_units,completed_units,total_probes,completed_probes,started_at,updated_at,expires_at,finished_at,last_error FROM scan_cycles WHERE id=?`, id).
		Scan(&cycle.ID, &cycle.JobID, &cycle.Job, &cycle.JobRevision, &cycle.ConfigHash, &cycle.ExecutionHash, &planJSON, &cycle.Status, &cycle.AttemptCount, &cycle.NoProgressAttempts, &cycle.TotalUnits, &cycle.CompletedUnits, &cycle.TotalProbes, &cycle.CompletedProbes, &started, &updated, &expires, &finished, &cycle.LastError)
	if errors.Is(err, sql.ErrNoRows) {
		return cycle, fmt.Errorf("%w: %s", ErrNoScanCycle, id)
	}
	if err != nil {
		return cycle, err
	}
	if err = json.Unmarshal(planJSON, &cycle.Plan); err != nil {
		return cycle, err
	}
	// scan_cycle_units is the authoritative source for dynamically generated
	// enrichment/UDP work. Keep the plan's aggregate counters aligned with the
	// durable cycle columns even when a newer reconciliation intentionally
	// avoids rewriting the large plan_json blob.
	cycle.Plan.TotalUnits = cycle.TotalUnits
	cycle.Plan.TotalProbes = cycle.TotalProbes
	cycle.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
	cycle.UpdatedAt, _ = time.Parse(time.RFC3339Nano, updated)
	cycle.ExpiresAt, _ = time.Parse(time.RFC3339Nano, expires)
	cycle.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
	return cycle, nil
}

// ScanCycleProbeTotals reports the durable execution categories for a
// resumable cycle without decoding checkpoint payloads. Naabu discovery and
// Nmap enrichment/UDP work use separate deployment budgets; keeping this
// aggregate query set-based lets the application reject an expansion before
// starting another scanner process.
func (s *Store) ScanCycleProbeTotals(ctx context.Context, cycleID string) (discovery, nmap int64, err error) {
	err = s.reader().QueryRowContext(ctx, `
		SELECT
			COALESCE(SUM(CASE WHEN json_extract(work_unit_json,'$.phase')='discovery' THEN CAST(json_extract(work_unit_json,'$.probes') AS INTEGER) ELSE 0 END),0),
			COALESCE(SUM(CASE WHEN json_extract(work_unit_json,'$.phase')<>'discovery' THEN CAST(json_extract(work_unit_json,'$.probes') AS INTEGER) ELSE 0 END),0)
		FROM scan_cycle_units WHERE cycle_id=?`, cycleID).Scan(&discovery, &nmap)
	return discovery, nmap, err
}

func (s *Store) GetActiveScanCycle(ctx context.Context, jobID string) (ScanCycleRecord, error) {
	var id string
	err := s.reader().QueryRowContext(ctx, `SELECT id FROM scan_cycles WHERE job_id=? AND status IN ('running','paused','stalled') ORDER BY started_at DESC LIMIT 1`, jobID).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return ScanCycleRecord{}, ErrNoScanCycle
	}
	if err != nil {
		return ScanCycleRecord{}, err
	}
	return s.GetScanCycle(ctx, id)
}

// GetLatestScanCycle returns the newest cycle for a job regardless of its
// terminal state. It is intentionally separate from GetActiveScanCycle: a
// completed, discarded, or expired cycle must remain visible in history but
// must never block creation of a fresh cycle.
func (s *Store) GetLatestScanCycle(ctx context.Context, jobID string) (ScanCycleRecord, error) {
	var id string
	err := s.reader().QueryRowContext(ctx, `SELECT id FROM scan_cycles WHERE job_id=? ORDER BY started_at DESC,id DESC LIMIT 1`, jobID).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return ScanCycleRecord{}, ErrNoScanCycle
	}
	if err != nil {
		return ScanCycleRecord{}, err
	}
	return s.GetScanCycle(ctx, id)
}

// ScanCycleExpiryNotified reports whether an expired cycle already produced
// its terminal scan record. Housekeeping can expire a cycle between schedule
// ticks; keeping this check separate lets the next trigger emit exactly one
// failure notification before a subsequent trigger starts a fresh cycle.
func (s *Store) ScanCycleExpiryNotified(ctx context.Context, cycleID string) (bool, error) {
	var count int
	err := s.reader().QueryRowContext(ctx, `SELECT COUNT(*) FROM scans WHERE cycle_id=? AND cycle_status='expired' AND status='timed_out'`, cycleID).Scan(&count)
	return count > 0, err
}

// ScanCycleHasScan reports whether a terminal cycle has already been promoted
// into scan history. The cycle is marked completed before the engine's final
// transaction, so a process crash in that small window must be recoverable on
// the next trigger rather than silently starting a brand-new cycle.
func (s *Store) ScanCycleHasScan(ctx context.Context, cycleID string) (bool, error) {
	var count int
	if err := s.reader().QueryRowContext(ctx, `SELECT COUNT(*) FROM scans WHERE cycle_id=?`, cycleID).Scan(&count); err != nil {
		return false, err
	}
	return count > 0, nil
}

func (s *Store) ListScanCycleUnitSummaries(ctx context.Context, cycleID string) ([]ScanCycleUnitSummary, error) {
	rows, err := s.reader().QueryContext(ctx, `SELECT cycle_id,sequence,work_unit_json,status,attempts,started_at,finished_at,last_error FROM scan_cycle_units WHERE cycle_id=? ORDER BY sequence`, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []ScanCycleUnitSummary
	for rows.Next() {
		var item ScanCycleUnitSummary
		var raw []byte
		var started, finished string
		if err := rows.Scan(&item.CycleID, &item.Sequence, &raw, &item.Status, &item.Attempts, &started, &finished, &item.LastError); err != nil {
			return nil, err
		}
		var unit scanner.WorkUnit
		if err := json.Unmarshal(raw, &unit); err != nil {
			return nil, err
		}
		item.Engine, item.Phase = unit.Engine, unit.Phase
		item.Protocol, item.Family, item.Ports, item.PortCount, item.Addresses, item.Probes = unit.Protocol, unit.Family, unit.Ports, unit.PortCount, len(unit.Addresses), unit.Probes
		item.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
		item.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
		out = append(out, item)
	}
	return out, rows.Err()
}

// ListScanCycleUnitSummariesPage returns a bounded progress page. Cycle plans
// can contain one unit per address/port batch, so exposing the entire list in
// one response lets a broad scan turn a status request into an unbounded read.
// Keep the legacy unpaged method above for internal callers and compatibility,
// while the HTTP endpoint uses this bounded projection.
func (s *Store) ListScanCycleUnitSummariesPage(ctx context.Context, cycleID string, limit, offset int) (Page[ScanCycleUnitSummary], error) {
	limit, offset = normalizePage(limit, offset)
	var page Page[ScanCycleUnitSummary]
	readDB := s.reader()
	if err := readDB.QueryRowContext(ctx, `SELECT COUNT(*) FROM scan_cycle_units WHERE cycle_id=?`, cycleID).Scan(&page.Total); err != nil {
		return page, err
	}
	rows, err := readDB.QueryContext(ctx, `SELECT cycle_id,sequence,work_unit_json,status,attempts,started_at,finished_at,last_error FROM scan_cycle_units WHERE cycle_id=? ORDER BY sequence LIMIT ? OFFSET ?`, cycleID, limit, offset)
	if err != nil {
		return page, err
	}
	defer rows.Close()
	for rows.Next() {
		var item ScanCycleUnitSummary
		var raw []byte
		var started, finished string
		if err := rows.Scan(&item.CycleID, &item.Sequence, &raw, &item.Status, &item.Attempts, &started, &finished, &item.LastError); err != nil {
			return page, err
		}
		var unit scanner.WorkUnit
		if err := json.Unmarshal(raw, &unit); err != nil {
			return page, err
		}
		item.Engine, item.Phase = unit.Engine, unit.Phase
		item.Protocol, item.Family, item.Ports, item.PortCount, item.Addresses, item.Probes = unit.Protocol, unit.Family, unit.Ports, unit.PortCount, len(unit.Addresses), unit.Probes
		item.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
		item.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
		page.Items = append(page.Items, item)
	}
	return page, rows.Err()
}

// StartScanCycleAttempt resets a unit left running by a process crash and
// atomically marks the cycle running for this attempt.
func (s *Store) StartScanCycleAttempt(ctx context.Context, id string) (ScanCycleRecord, error) {
	now := time.Now().UTC()
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	defer tx.Rollback()
	var status, expires string
	if err = tx.QueryRowContext(ctx, `SELECT status,expires_at FROM scan_cycles WHERE id=?`, id).Scan(&status, &expires); errors.Is(err, sql.ErrNoRows) {
		return ScanCycleRecord{}, fmt.Errorf("%w: %s", ErrNoScanCycle, id)
	} else if err != nil {
		return ScanCycleRecord{}, err
	}
	if status != "paused" && status != "stalled" && status != "running" {
		return ScanCycleRecord{}, ErrCycleNotResumable
	}
	if expiry, parseErr := time.Parse(time.RFC3339Nano, expires); parseErr == nil && !expiry.IsZero() && !now.Before(expiry) {
		stamp := now.Format(time.RFC3339Nano)
		transition, transitionErr := tx.ExecContext(ctx, `UPDATE scan_cycles SET status='expired',updated_at=?,finished_at=?,last_error='scan cycle exceeded its resume window' WHERE id=? AND status IN ('running','paused','stalled')`, stamp, stamp, id)
		if transitionErr != nil {
			return ScanCycleRecord{}, transitionErr
		}
		changed, _ := transition.RowsAffected()
		if changed != 1 {
			// Another writer may have completed, discarded, or expired the cycle
			// after our initial read. Do not clear its checkpoints in that case;
			// the terminal transition (and any cleanup) belongs to that writer.
			return ScanCycleRecord{}, ErrCycleNotResumable
		}
		// Commit the terminal transition before clearing checkpoint payloads. The
		// cleanup is deliberately performed in bounded follow-up transactions so a
		// full-range cycle cannot hold the writer while every unit is rewritten.
		// Without committing first, the deferred rollback would undo expiry and the
		// next trigger could rediscover the same cycle as resumable.
		if err = tx.Commit(); err != nil {
			return ScanCycleRecord{}, err
		}
		// Cleanup is best effort here: the terminal state is already durable and
		// the regular retention pass retries any payloads left behind by a canceled
		// context or a transient database error.
		_ = s.clearExpiredCyclePayloads(ctx, []string{id})
		return ScanCycleRecord{}, ErrCycleNotResumable
	}
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycle_units SET status='pending',started_at='',last_error=last_error WHERE cycle_id=? AND status='running'`, id); err != nil {
		return ScanCycleRecord{}, err
	}
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycles SET status='running',attempt_count=attempt_count+1,updated_at=? WHERE id=? AND status IN ('paused','stalled','running')`, now.Format(time.RFC3339Nano), id); err != nil {
		return ScanCycleRecord{}, err
	}
	if err = tx.Commit(); err != nil {
		return ScanCycleRecord{}, err
	}
	return s.GetScanCycle(ctx, id)
}

func (s *Store) NextScanCycleUnit(ctx context.Context, cycleID string) (ScanCycleUnit, error) {
	var unit ScanCycleUnit
	var raw, snapshot []byte
	var started, finished string
	status, statusErr := s.scanCycleStatus(ctx, cycleID)
	if statusErr != nil {
		return unit, statusErr
	}
	if status != "running" {
		if status == "completed" {
			return unit, ErrNoPendingUnit
		}
		return unit, ErrCycleNotResumable
	}
	err := s.reader().QueryRowContext(ctx, `SELECT cycle_id,sequence,work_unit_json,status,attempts,snapshot_json,started_at,finished_at,last_error FROM scan_cycle_units WHERE cycle_id=? AND status='pending' ORDER BY sequence LIMIT 1`, cycleID).
		Scan(&unit.CycleID, &unit.Sequence, &raw, &unit.Status, &unit.Attempts, &snapshot, &started, &finished, &unit.LastError)
	if errors.Is(err, sql.ErrNoRows) {
		return unit, ErrNoPendingUnit
	}
	if err != nil {
		return unit, err
	}
	if err = json.Unmarshal(raw, &unit.Unit); err != nil {
		return unit, err
	}
	if len(snapshot) > 0 && string(snapshot) != "{}" && string(snapshot) != "null" {
		if err = json.Unmarshal(snapshot, &unit.Snapshot); err != nil {
			return unit, err
		}
	}
	unit.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
	unit.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
	return unit, nil
}

func (s *Store) ClaimScanCycleUnit(ctx context.Context, cycleID string, sequence int) (ScanCycleUnit, error) {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	result, err := s.DB.ExecContext(ctx, `UPDATE scan_cycle_units SET status='running',attempts=attempts+1,started_at=?,last_error='' WHERE cycle_id=? AND sequence=? AND status='pending' AND EXISTS (SELECT 1 FROM scan_cycles WHERE id=? AND status='running')`, now, cycleID, sequence, cycleID)
	if err != nil {
		return ScanCycleUnit{}, err
	}
	if count, _ := result.RowsAffected(); count != 1 {
		if status, statusErr := s.scanCycleStatus(ctx, cycleID); statusErr != nil {
			return ScanCycleUnit{}, statusErr
		} else if status != "running" {
			return ScanCycleUnit{}, ErrCycleNotResumable
		}
		return ScanCycleUnit{}, ErrNoPendingUnit
	}
	return s.getScanCycleUnit(ctx, cycleID, sequence)
}

func (s *Store) scanCycleStatus(ctx context.Context, cycleID string) (string, error) {
	var status string
	err := s.reader().QueryRowContext(ctx, `SELECT status FROM scan_cycles WHERE id=?`, cycleID).Scan(&status)
	if errors.Is(err, sql.ErrNoRows) {
		return "", fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
	}
	return status, err
}

func (s *Store) getScanCycleUnit(ctx context.Context, cycleID string, sequence int) (ScanCycleUnit, error) {
	var unit ScanCycleUnit
	var raw, snapshot []byte
	var started, finished string
	err := s.reader().QueryRowContext(ctx, `SELECT cycle_id,sequence,work_unit_json,status,attempts,snapshot_json,started_at,finished_at,last_error FROM scan_cycle_units WHERE cycle_id=? AND sequence=?`, cycleID, sequence).
		Scan(&unit.CycleID, &unit.Sequence, &raw, &unit.Status, &unit.Attempts, &snapshot, &started, &finished, &unit.LastError)
	if err != nil {
		return unit, err
	}
	if err = json.Unmarshal(raw, &unit.Unit); err != nil {
		return unit, err
	}
	if len(snapshot) > 0 && string(snapshot) != "{}" && string(snapshot) != "null" {
		_ = json.Unmarshal(snapshot, &unit.Snapshot)
	}
	unit.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
	unit.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
	return unit, nil
}

func (s *Store) CompleteScanCycleUnit(ctx context.Context, cycleID string, sequence int, snapshot model.Snapshot) error {
	raw, err := json.Marshal(snapshot)
	if err != nil {
		return err
	}
	now := time.Now().UTC()
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var status string
	var unitRaw []byte
	if err = tx.QueryRowContext(ctx, `SELECT status,work_unit_json FROM scan_cycle_units WHERE cycle_id=? AND sequence=?`, cycleID, sequence).Scan(&status, &unitRaw); err != nil {
		return err
	}
	if status == "completed" {
		return nil
	}
	if status != "running" {
		return fmt.Errorf("scan cycle unit %d is not running", sequence)
	}
	var cycleStatus string
	if err = tx.QueryRowContext(ctx, `SELECT status FROM scan_cycles WHERE id=?`, cycleID).Scan(&cycleStatus); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
		}
		return err
	}
	if cycleStatus != "running" {
		return ErrCycleNotResumable
	}
	var unit scanner.WorkUnit
	if err = json.Unmarshal(unitRaw, &unit); err != nil {
		return err
	}
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycle_units SET status='completed',snapshot_json=?,finished_at=?,last_error='' WHERE cycle_id=? AND sequence=?`, raw, now.Format(time.RFC3339Nano), cycleID, sequence); err != nil {
		return err
	}
	cycleUpdate, err := tx.ExecContext(ctx, `UPDATE scan_cycles SET completed_units=completed_units+1,completed_probes=completed_probes+?,updated_at=? WHERE id=? AND status='running'`, unit.Probes, now.Format(time.RFC3339Nano), cycleID)
	if err != nil {
		return err
	}
	if count, _ := cycleUpdate.RowsAffected(); count != 1 {
		return ErrCycleNotResumable
	}
	return tx.Commit()
}

func (s *Store) RetryScanCycleUnit(ctx context.Context, cycleID string, sequence int, lastError string) error {
	result, err := s.DB.ExecContext(ctx, `UPDATE scan_cycle_units SET status='pending',last_error=? WHERE cycle_id=? AND sequence=? AND status='running' AND EXISTS (SELECT 1 FROM scan_cycles WHERE id=? AND status='running')`, trimCycleError(lastError), cycleID, sequence, cycleID)
	if err != nil {
		return err
	}
	if count, _ := result.RowsAffected(); count == 1 {
		return nil
	}
	status, statusErr := s.scanCycleStatus(ctx, cycleID)
	if statusErr != nil {
		return statusErr
	}
	if status != "running" {
		return ErrCycleNotResumable
	}
	return ErrNoPendingUnit
}

func (s *Store) SplitScanCycleUnit(ctx context.Context, cycleID string, sequence int, first, second scanner.WorkUnit, lastError string) error {
	firstRaw, err := json.Marshal(first)
	if err != nil {
		return err
	}
	secondRaw, err := json.Marshal(second)
	if err != nil {
		return err
	}
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var status string
	var originalRaw []byte
	if err = tx.QueryRowContext(ctx, `SELECT status,work_unit_json FROM scan_cycle_units WHERE cycle_id=? AND sequence=?`, cycleID, sequence).Scan(&status, &originalRaw); err != nil {
		return err
	}
	if status == "completed" {
		return nil
	}
	if status != "running" {
		return ErrCycleNotResumable
	}
	var cycleStatus string
	if err = tx.QueryRowContext(ctx, `SELECT status FROM scan_cycles WHERE id=?`, cycleID).Scan(&cycleStatus); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
		}
		return err
	}
	if cycleStatus != "running" {
		return ErrCycleNotResumable
	}
	var original scanner.WorkUnit
	if err := json.Unmarshal(originalRaw, &original); err != nil {
		return err
	}
	var next int
	if err = tx.QueryRowContext(ctx, `SELECT COALESCE(MAX(sequence),-1)+1 FROM scan_cycle_units WHERE cycle_id=?`, cycleID).Scan(&next); err != nil {
		return err
	}
	second.Sequence = next
	secondRaw, err = json.Marshal(second)
	if err != nil {
		return err
	}
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycle_units SET work_unit_json=?,identity=?,status='pending',last_error=? WHERE cycle_id=? AND sequence=?`, firstRaw, scanCycleUnitIdentity(first), trimCycleError(lastError), cycleID, sequence); err != nil {
		return err
	}
	if _, err = tx.ExecContext(ctx, `INSERT INTO scan_cycle_units(cycle_id,sequence,work_unit_json,identity,status,attempts,snapshot_json,started_at,finished_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?)`, cycleID, next, secondRaw, scanCycleUnitIdentity(second), "pending", 0, []byte(`{}`), "", "", ""); err != nil {
		return err
	}
	probeDelta := first.Probes + second.Probes - original.Probes
	cycleUpdate, err := tx.ExecContext(ctx, `UPDATE scan_cycles SET total_units=total_units+1,total_probes=total_probes+?,updated_at=?,last_error=? WHERE id=? AND status='running'`, probeDelta, time.Now().UTC().Format(time.RFC3339Nano), trimCycleError(lastError), cycleID)
	if err != nil {
		return err
	}
	if count, _ := cycleUpdate.RowsAffected(); count != 1 {
		return ErrCycleNotResumable
	}
	return tx.Commit()
}

func (s *Store) PauseScanCycle(ctx context.Context, cycleID string, noProgress bool, lastError string) (ScanCycleRecord, error) {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	query := `UPDATE scan_cycles SET status='paused',no_progress_attempts=CASE WHEN ? THEN no_progress_attempts+1 ELSE 0 END,updated_at=?,last_error=? WHERE id=? AND status IN ('running','paused','stalled')`
	if _, err := s.DB.ExecContext(ctx, query, noProgress, now, trimCycleError(lastError), cycleID); err != nil {
		return ScanCycleRecord{}, err
	}
	return s.GetScanCycle(ctx, cycleID)
}

func (s *Store) MarkScanCycleStalled(ctx context.Context, cycleID, lastError string) (ScanCycleRecord, error) {
	if _, err := s.DB.ExecContext(ctx, `UPDATE scan_cycles SET status='stalled',updated_at=?,last_error=? WHERE id=? AND status IN ('running','paused','stalled')`, time.Now().UTC().Format(time.RFC3339Nano), trimCycleError(lastError), cycleID); err != nil {
		return ScanCycleRecord{}, err
	}
	return s.GetScanCycle(ctx, cycleID)
}

func (s *Store) CompleteScanCycle(ctx context.Context, cycleID string) (ScanCycleRecord, error) {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	defer tx.Rollback()
	var status string
	var completed, total int
	if err = tx.QueryRowContext(ctx, `SELECT status,completed_units,total_units FROM scan_cycles WHERE id=?`, cycleID).Scan(&status, &completed, &total); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ScanCycleRecord{}, fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
		}
		return ScanCycleRecord{}, err
	}
	if status == "completed" {
		_ = tx.Rollback()
		return s.GetScanCycle(ctx, cycleID)
	}
	if status != "running" {
		return ScanCycleRecord{}, ErrCycleNotResumable
	}
	if completed != total {
		return ScanCycleRecord{}, fmt.Errorf("%w: %d of %d units completed", ErrCycleIncomplete, completed, total)
	}
	// Keep the completed unit payloads until the merged scan is promoted. The
	// promotion is a separate transaction, and retaining this short-lived
	// recovery source means a process crash between these operations cannot lose
	// a completed cycle. SaveScan/FinalizeManagedScan reclaim the payloads after
	// the immutable scan and its indexes are committed.
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycles SET status='completed',updated_at=?,finished_at=?,last_error='' WHERE id=? AND status='running'`, now, now, cycleID); err != nil {
		return ScanCycleRecord{}, err
	}
	if err = tx.Commit(); err != nil {
		return ScanCycleRecord{}, err
	}
	return s.GetScanCycle(ctx, cycleID)
}

func (s *Store) DiscardScanCycle(ctx context.Context, cycleID string) error {
	tx, err := s.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var status string
	if err = tx.QueryRowContext(ctx, `SELECT status FROM scan_cycles WHERE id=?`, cycleID).Scan(&status); errors.Is(err, sql.ErrNoRows) {
		return ErrNoScanCycle
	} else if err != nil {
		return err
	}
	if status != "paused" && status != "stalled" {
		return ErrCycleNotResumable
	}
	stamp := time.Now().UTC().Format(time.RFC3339Nano)
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycles SET status='discarded',updated_at=?,finished_at=?,last_error='discarded by administrator' WHERE id=? AND status IN ('paused','stalled')`, stamp, stamp, cycleID); err != nil {
		return err
	}
	if _, err = tx.ExecContext(ctx, `DELETE FROM scan_cycle_units WHERE cycle_id=?`, cycleID); err != nil {
		return err
	}
	return tx.Commit()
}

func (s *Store) ExpireScanCycles(ctx context.Context, now time.Time) (int64, error) {
	if now.IsZero() {
		now = time.Now().UTC()
	}
	stamp := now.UTC().Format(time.RFC3339Nano)
	var total int64
	for {
		if err := ctx.Err(); err != nil {
			return total, err
		}
		tx, err := s.DB.BeginTx(ctx, nil)
		if err != nil {
			return total, err
		}
		ids, err := expiredScanCycleIDs(ctx, tx, stamp)
		if err != nil {
			_ = tx.Rollback()
			return total, err
		}
		if len(ids) == 0 {
			if err := tx.Commit(); err != nil {
				return total, err
			}
			return total, nil
		}
		placeholders := make([]string, len(ids))
		args := []any{stamp, stamp}
		for i, id := range ids {
			placeholders[i] = "?"
			args = append(args, id)
		}
		query := `UPDATE scan_cycles SET status='expired',updated_at=?,finished_at=?,last_error='scan cycle exceeded its resume window' WHERE status IN ('running','paused','stalled') AND id IN (` + strings.Join(placeholders, ",") + `)`
		result, err := tx.ExecContext(ctx, query, args...)
		if err != nil {
			_ = tx.Rollback()
			return total, err
		}
		changed, _ := result.RowsAffected()
		if err := tx.Commit(); err != nil {
			return total, err
		}
		total += changed
		if err := s.clearExpiredCyclePayloads(ctx, ids); err != nil {
			return total, err
		}
	}
}

func expiredScanCycleIDs(ctx context.Context, tx *sql.Tx, stamp string) ([]string, error) {
	rows, err := tx.QueryContext(ctx, `SELECT id FROM scan_cycles WHERE status IN ('running','paused','stalled') AND expires_at<=? ORDER BY expires_at,id LIMIT ?`, stamp, scanCycleReconcileBatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	ids := make([]string, 0, scanCycleReconcileBatchSize)
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// clearExpiredCyclePayloads reclaims potentially large checkpoint documents
// after the terminal cycle transition. The cycle IDs are already bounded by
// ExpireScanCycles; each update is additionally limited to one batch of unit
// rows so a single broad cycle cannot monopolize the writer connection.
func (s *Store) clearExpiredCyclePayloads(ctx context.Context, ids []string) error {
	if len(ids) == 0 {
		return nil
	}
	placeholders := make([]string, len(ids))
	args := make([]any, len(ids))
	for i, id := range ids {
		placeholders[i] = "?"
		args[i] = id
	}
	args = append(args, scanCycleReconcileBatchSize)
	query := `UPDATE scan_cycle_units SET snapshot_json='{}',last_error='cycle expired' WHERE rowid IN (SELECT rowid FROM scan_cycle_units WHERE cycle_id IN (` + strings.Join(placeholders, ",") + `) AND snapshot_json<>'{}' ORDER BY rowid LIMIT ?)`
	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		result, err := s.DB.ExecContext(ctx, query, args...)
		if err != nil {
			return err
		}
		count, _ := result.RowsAffected()
		if count < scanCycleReconcileBatchSize {
			return nil
		}
	}
}

func (s *Store) LoadScanCycleFragments(ctx context.Context, cycleID string) (scanner.WorkPlan, []model.Snapshot, error) {
	cycle, err := s.GetScanCycle(ctx, cycleID)
	if err != nil {
		return scanner.WorkPlan{}, nil, err
	}
	rows, err := s.reader().QueryContext(ctx, `SELECT snapshot_json FROM scan_cycle_units WHERE cycle_id=? AND status='completed' ORDER BY sequence`, cycleID)
	if err != nil {
		return scanner.WorkPlan{}, nil, err
	}
	defer rows.Close()
	var fragments []model.Snapshot
	for rows.Next() {
		var raw []byte
		if err = rows.Scan(&raw); err != nil {
			return scanner.WorkPlan{}, nil, err
		}
		var snapshot model.Snapshot
		if err = json.Unmarshal(raw, &snapshot); err != nil {
			return scanner.WorkPlan{}, nil, err
		}
		fragments = append(fragments, snapshot)
	}
	return cycle.Plan, fragments, rows.Err()
}

func trimCycleError(raw string) string {
	raw = strings.TrimSpace(raw)
	if len(raw) > 500 {
		return raw[:500] + "…"
	}
	return raw
}
