package store

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/crypt0rr/edgewatch/internal/config"
	"github.com/crypt0rr/edgewatch/internal/model"
	"github.com/crypt0rr/edgewatch/internal/scanner"
	"github.com/google/uuid"
)

var (
	// ErrNoScanCycle reports an unknown scan cycle, or one of another
	// tenant. It matches ErrNotFound, and its message is still "scan cycle
	// not found".
	ErrNoScanCycle       = fmt.Errorf("scan cycle %w", ErrNotFound)
	ErrNoPendingUnit     = errors.New("scan cycle has no pending work")
	ErrCycleNotResumable = errors.New("scan cycle is not resumable")
	ErrCycleIncomplete   = errors.New("scan cycle is incomplete")
	ErrMissingCheckpoint = errors.New("scan cycle checkpoint is missing")
)

// scanCycleReconcileBatchSize bounds the amount of discovery evidence and
// dynamic work generated by one writer transaction. A full-range Naabu cycle
// can contain thousands of address batches; processing them in bounded
// chunks keeps the writer available to foreground scan/checkpoint writes.
const scanCycleReconcileBatchSize = 64

// ScanCycleRecord is the durable state for a complete scope scan that may
// require more than one attempt. The plan includes the normalized job and
// pinned DNS expansion so a resumed cycle never silently changes scope.
//
// A cycle read from the store carries only the plan's creation time, job, and
// totals: its targets, scopes, and DNS expansion, which grow with the scope,
// are read only where they are used, by LoadScanCycleFragments and the
// enrichment reconciliation. Its units are the rows of scan_cycle_units.
type ScanCycleRecord struct {
	ID                 string
	JobID              string
	Job                string
	JobRevision        int64
	ConfigHash         string
	ExecutionHash      string
	BaselineEpoch      int64
	Plan               scanner.WorkPlan
	Status             string
	AttemptCount       int
	NoProgressAttempts int
	TotalUnits         int
	CompletedUnits     int
	TotalProbes        int64
	CompletedProbes    int64
	StartedAt          time.Time
	UpdatedAt          time.Time
	ExpiresAt          time.Time
	FinishedAt         time.Time
	LastError          string
}

// ScanCycleSummary is the bounded active-cycle projection included in the
// polled job list. Unlike ScanCycleRecord it does not decode the potentially
// large pinned work plan.
type ScanCycleSummary struct {
	ID                 string
	JobID              string
	JobRevision        int64
	Status             string
	AttemptCount       int
	NoProgressAttempts int
	TotalUnits         int
	CompletedUnits     int
	TotalProbes        int64
	CompletedProbes    int64
	StartedAt          time.Time
	UpdatedAt          time.Time
	ExpiresAt          time.Time
	FinishedAt         time.Time
	LastError          string
}

// ScanCycleUnit is one independently persisted Nmap invocation.
type ScanCycleUnit struct {
	CycleID    string
	Sequence   int
	Unit       scanner.WorkUnit
	Status     string
	Attempts   int
	Failures   int
	Snapshot   model.Snapshot
	StartedAt  time.Time
	FinishedAt time.Time
	LastError  string
}

// ScanCycleUnitSummary is the safe progress view returned to the web console.
// It omits checkpoint payloads, which can be very large for a full-range job.
type ScanCycleUnitSummary struct {
	CycleID    string    `json:"cycle_id"`
	Sequence   int       `json:"sequence"`
	Engine     string    `json:"engine,omitempty"`
	Phase      string    `json:"phase,omitempty"`
	Protocol   string    `json:"protocol"`
	Family     int       `json:"family"`
	Ports      string    `json:"ports"`
	PortCount  int       `json:"port_count"`
	Addresses  int       `json:"addresses"`
	Probes     int64     `json:"probes"`
	Status     string    `json:"status"`
	Attempts   int       `json:"attempts"`
	Failures   int       `json:"failures"`
	StartedAt  time.Time `json:"started_at"`
	FinishedAt time.Time `json:"finished_at"`
	LastError  string    `json:"last_error,omitempty"`
}

// CreateScanCycle stores a new paused cycle with its planned units. It is
// the daemon's writer: the cycle belongs to its job's tenant, which the
// scan_cycles foreign key requires to exist.
func (ss *SystemStore) CreateScanCycle(ctx context.Context, cycle ScanCycleRecord) (ScanCycleRecord, error) {
	if cycle.JobID == "" || cycle.Job == "" {
		return ScanCycleRecord{}, errors.New("scan cycle job is required")
	}
	if len(cycle.Plan.Units) == 0 {
		return ScanCycleRecord{}, errors.New("scan cycle has no work units")
	}
	if cycle.ID == "" {
		cycle.ID = uuid.NewString()
	}
	now := cycle.StartedAt.UTC()
	if now.IsZero() {
		now = time.Now().UTC()
	}
	cycle.StartedAt = now
	if cycle.UpdatedAt.IsZero() {
		cycle.UpdatedAt = now
	}
	if cycle.ExpiresAt.IsZero() {
		cycle.ExpiresAt = now.Add(8 * 24 * time.Hour)
	}
	cycle.Status = "paused"
	cycle.TotalUnits = len(cycle.Plan.Units)
	// Treat the persisted unit list as the source of truth for progress. This
	// also keeps alternate scanners safe when they omit the aggregate totals in
	// their plan; a resumed cycle must never advertise zero work for non-empty
	// units or over-count probes after a split.
	var plannedProbes int64
	for _, unit := range cycle.Plan.Units {
		plannedProbes += unit.Probes
	}
	cycle.TotalProbes = plannedProbes
	cycle.Plan.TotalUnits = cycle.TotalUnits
	cycle.Plan.TotalProbes = plannedProbes
	// The units are stored once, as scan_cycle_units rows, and no reader of
	// plan_json takes them from there.
	stored := cycle.Plan
	stored.Units = nil
	planJSON, err := json.Marshal(stored)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	tx, err := ss.store.DB.BeginTx(ctx, nil)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	defer tx.Rollback()
	_, err = tx.ExecContext(ctx, `INSERT INTO scan_cycles(id,job_id,job,job_revision,config_hash,execution_hash,baseline_epoch,plan_json,status,attempt_count,no_progress_attempts,total_units,completed_units,total_probes,completed_probes,started_at,updated_at,expires_at,finished_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
		cycle.ID, cycle.JobID, cycle.Job, cycle.JobRevision, cycle.ConfigHash, cycle.ExecutionHash, cycle.BaselineEpoch, planJSON, cycle.Status, cycle.AttemptCount, cycle.NoProgressAttempts, cycle.TotalUnits, cycle.CompletedUnits, cycle.TotalProbes, cycle.CompletedProbes, sqliteTimestamp(cycle.StartedAt), sqliteTimestamp(cycle.UpdatedAt), sqliteTimestamp(cycle.ExpiresAt), "", cycle.LastError)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	for _, unit := range cycle.Plan.Units {
		raw, marshalErr := json.Marshal(unit)
		if marshalErr != nil {
			return ScanCycleRecord{}, marshalErr
		}
		if _, err = tx.ExecContext(ctx, `INSERT INTO scan_cycle_units(cycle_id,sequence,work_unit_json,identity,phase,probes,status,attempts,snapshot_json,started_at,finished_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`, cycle.ID, unit.Sequence, raw, scanCycleUnitIdentity(unit), unit.Phase, unit.Probes, "pending", 0, []byte(`{}`), "", "", ""); err != nil {
			return ScanCycleRecord{}, err
		}
	}
	if err = tx.Commit(); err != nil {
		return ScanCycleRecord{}, err
	}
	return cycle, nil
}

// ReconcileScanCycleEnrichment expands a phase-aware Naabu cycle from durable
// discovery checkpoints. Each bounded batch marks its discovery rows in the
// same transaction that creates the corresponding Nmap enrichment work. The
// method drains all available batches, but every transaction is capped by
// scanCycleReconcileBatchSize and can be interrupted by the caller's context.
//
// Dynamic units are authoritative in scan_cycle_units. We deliberately do not
// rewrite the potentially very large plan_json blob for every discovery batch;
// this keeps reconciliation linear in the amount of newly completed evidence.
// GetScanCycle reports the authoritative counters from scan_cycles, while
// LoadScanCycleFragments uses the unit table when promoting a completed cycle.
func (ss *SystemStore) ReconcileScanCycleEnrichment(ctx context.Context, cycleID string) error {
	cycle, err := ss.scanCycle(ctx, cycleID)
	if err != nil {
		return err
	}
	if cycle.Status != "running" && cycle.Status != "paused" && cycle.Status != "stalled" {
		return nil
	}
	if cycle.Plan.Job.TCP == nil || cycle.Plan.Job.TCP.Engine != config.EngineNaabuNmap {
		return nil
	}
	if cycle.Plan, err = ss.scanCyclePlan(ctx, cycleID); err != nil {
		return err
	}

	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		worked, batchErr := ss.reconcileScanCycleEnrichmentBatch(ctx, cycleID, cycle.Plan)
		if batchErr != nil {
			return batchErr
		}
		if !worked {
			return nil
		}
	}
}

// reconcileScanCycleEnrichmentBatch performs one bounded reconciliation
// transaction. The bool reports whether more checkpoint or dynamic work was
// committed and lets the caller drain additional batches without making the
// writer transaction itself unbounded.
func (ss *SystemStore) reconcileScanCycleEnrichmentBatch(ctx context.Context, cycleID string, plan scanner.WorkPlan) (bool, error) {
	tx, err := ss.store.DB.BeginTx(ctx, nil)
	if err != nil {
		return false, err
	}
	defer tx.Rollback()
	var status, cycleJob string
	if err := tx.QueryRowContext(ctx, `SELECT status,job_id FROM scan_cycles WHERE id=?`, cycleID).Scan(&status, &cycleJob); errors.Is(err, sql.ErrNoRows) {
		return false, fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
	} else if err != nil {
		return false, err
	}
	if status != "running" && status != "paused" && status != "stalled" {
		return false, tx.Commit()
	}

	// Phase is maintained as an indexed scalar on each unit, so SQLite can
	// count completed discovery rows without invoking JSON1 or loading any
	// checkpoint payload. Only the first bounded batch is decoded below.
	var discoveryCount, completedDiscoveryCount int
	if err := tx.QueryRowContext(ctx, `SELECT COUNT(*),COALESCE(SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END),0) FROM scan_cycle_units WHERE cycle_id=? AND phase='discovery'`, cycleID).Scan(&discoveryCount, &completedDiscoveryCount); err != nil {
		return false, err
	}
	if discoveryCount == 0 {
		return false, tx.Commit()
	}
	discoveryComplete := completedDiscoveryCount == discoveryCount

	type discoveryRow struct {
		sequence int
		unit     scanner.WorkUnit
		snapshot model.Snapshot
	}
	rows, err := tx.QueryContext(ctx, `SELECT u.sequence,u.work_unit_json,u.snapshot_json FROM scan_cycle_units AS u WHERE u.cycle_id=? AND u.status='completed' AND u.phase='discovery' AND NOT EXISTS (SELECT 1 FROM scan_cycle_discovery_checkpoints AS c WHERE c.cycle_id=u.cycle_id AND c.sequence=u.sequence) ORDER BY u.sequence LIMIT ?`, cycleID, scanCycleReconcileBatchSize)
	if err != nil {
		return false, err
	}
	var pending []discoveryRow
	for rows.Next() {
		var row discoveryRow
		var unitRaw, snapshotRaw []byte
		if err := rows.Scan(&row.sequence, &unitRaw, &snapshotRaw); err != nil {
			rows.Close()
			return false, err
		}
		if err := json.Unmarshal(unitRaw, &row.unit); err != nil {
			rows.Close()
			return false, err
		}
		if len(snapshotRaw) > 0 && string(snapshotRaw) != "{}" && string(snapshotRaw) != "null" {
			if err := json.Unmarshal(snapshotRaw, &row.snapshot); err != nil {
				rows.Close()
				return false, err
			}
		}
		pending = append(pending, row)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return false, err
	}
	rows.Close()

	// Gather one deterministic port set per effective address from only this
	// batch. Discovery address batches are disjoint; unioning within the batch
	// still protects against duplicate host observations during recovery.
	// Every positive TCP port the job currently tracks (baseline, open
	// incidents, pending and suppressed changes) is included as a bounded
	// safety net: Naabu emits positive discoveries only, so a transient miss
	// must still be confirmed by Nmap before EdgeWatch records a closure.
	portsByAddress := map[string]map[int]struct{}{}
	batchAddresses := map[string]struct{}{}
	for _, row := range pending {
		for _, address := range row.unit.Addresses {
			if normalized := normalizeCycleAddress(address); normalized != "" {
				batchAddresses[normalized] = struct{}{}
			}
		}
		for _, host := range row.snapshot.Hosts {
			if normalized := normalizeCycleAddress(host.Address); normalized != "" {
				batchAddresses[normalized] = struct{}{}
			}
		}
	}
	expectedPorts, expectedErr := expectedTCPPortsTx(ctx, tx, cycleJob, plan.Targets)
	if expectedErr != nil {
		return false, expectedErr
	}
	for address, ports := range expectedPorts {
		if _, inBatch := batchAddresses[address]; !inBatch {
			continue
		}
		if len(ports) == 0 {
			continue
		}
		set := portsByAddress[address]
		if set == nil {
			set = map[int]struct{}{}
			portsByAddress[address] = set
		}
		for port := range ports {
			set[port] = struct{}{}
		}
	}
	for _, row := range pending {
		for _, host := range row.snapshot.Hosts {
			address := normalizeCycleAddress(host.Address)
			if address == "" {
				continue
			}
			for _, protocol := range host.Protocols {
				if protocol.Protocol != "tcp" || protocol.DiscoveryEngine != "naabu" {
					continue
				}
				set := portsByAddress[address]
				if set == nil {
					set = map[int]struct{}{}
					portsByAddress[address] = set
				}
				for _, port := range protocol.DiscoveredPorts {
					if port.Port >= 1 && port.Port <= 65535 {
						set[port.Port] = struct{}{}
					}
				}
			}
		}
	}

	type discoveryGroup struct {
		family    int
		ports     []int
		addresses []string
	}
	groups := map[string]*discoveryGroup{}
	for address, set := range portsByAddress {
		if len(set) == 0 {
			continue
		}
		ports := make([]int, 0, len(set))
		for port := range set {
			ports = append(ports, port)
		}
		sort.Ints(ports)
		family := 4
		if ip := net.ParseIP(address); ip != nil && ip.To4() == nil {
			family = 6
		}
		key := fmt.Sprintf("%d\x00%s", family, formatCyclePorts(ports))
		group := groups[key]
		if group == nil {
			group = &discoveryGroup{family: family, ports: ports}
			groups[key] = group
		}
		group.addresses = append(group.addresses, address)
	}
	groupKeys := make([]string, 0, len(groups))
	for key := range groups {
		groupKeys = append(groupKeys, key)
	}
	sort.Strings(groupKeys)

	var nextSequence int
	if err := tx.QueryRowContext(ctx, `SELECT COALESCE(MAX(sequence),-1)+1 FROM scan_cycle_units WHERE cycle_id=?`, cycleID).Scan(&nextSequence); err != nil {
		return false, err
	}
	var added []scanner.WorkUnit
	newIdentities := make(map[string]struct{})
	factor := boolFactor(plan.Job.TCP.ServiceDetection)
	enrichmentTemplate := plan.Job.TCP.EnrichmentArgs
	if len(enrichmentTemplate) == 0 {
		// Older Naabu profiles used nmap_args for the confirmation command.
		// Match the scanner executor's compatibility fallback so persisted
		// checkpoints never describe a multi-address unit that the template
		// can only render one address for.
		enrichmentTemplate = plan.Job.TCP.NmapArgs
	}
	addressBatchSize := scanner.NmapAddressBatchLimit(enrichmentTemplate)
	for _, key := range groupKeys {
		group := groups[key]
		sort.Strings(group.addresses)
		for addressStart := 0; addressStart < len(group.addresses); addressStart += addressBatchSize {
			addressEnd := addressStart + addressBatchSize
			if addressEnd > len(group.addresses) {
				addressEnd = len(group.addresses)
			}
			addresses := append([]string(nil), group.addresses[addressStart:addressEnd]...)
			perChunk := scanner.MaxWorkUnitPorts
			if capacity := int(scanner.MaxWorkUnitProbes / (int64(len(addresses)) * factor)); capacity > 0 && perChunk > capacity {
				perChunk = capacity
			}
			if perChunk < 1 {
				perChunk = 1
			}
			for portStart := 0; portStart < len(group.ports); portStart += perChunk {
				portEnd := portStart + perChunk
				if portEnd > len(group.ports) {
					portEnd = len(group.ports)
				}
				portChunk := group.ports[portStart:portEnd]
				unit := scanner.WorkUnit{Sequence: nextSequence, Engine: config.EngineNmap, Phase: "enrichment", Protocol: "tcp", Family: group.family, Targets: subsetCycleTargets(plan.Targets, addresses), Addresses: addresses, Ports: formatCyclePorts(portChunk), PortCount: len(portChunk), Probes: int64(len(addresses)) * int64(len(portChunk)) * factor}
				nextSequence++
				identity := scanCycleUnitIdentity(unit)
				if _, exists := newIdentities[identity]; exists {
					continue
				}
				exists, err := scanCycleUnitIdentityExists(ctx, tx, cycleID, identity)
				if err != nil {
					return false, err
				}
				if exists {
					continue
				}
				added = append(added, unit)
				newIdentities[identity] = struct{}{}
			}
		}
	}

	// Only append UDP after the final discovery batch has been checkpointed.
	// Otherwise a large recovery batch could place UDP ahead of enrichment work
	// belonging to later discovery rows.
	morePending := false
	if len(pending) > 0 {
		lastSequence := pending[len(pending)-1].sequence
		if err := tx.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM scan_cycle_units AS u WHERE u.cycle_id=? AND u.status='completed' AND u.phase='discovery' AND u.sequence>? AND NOT EXISTS (SELECT 1 FROM scan_cycle_discovery_checkpoints AS c WHERE c.cycle_id=u.cycle_id AND c.sequence=u.sequence))`, cycleID, lastSequence).Scan(&morePending); err != nil {
			return false, err
		}
	}
	if discoveryComplete && !morePending && plan.Job.UDP != nil {
		var udpCount int
		if err := tx.QueryRowContext(ctx, `SELECT COUNT(*) FROM scan_cycle_units WHERE cycle_id=? AND phase='udp'`, cycleID).Scan(&udpCount); err != nil {
			return false, err
		}
		if udpCount == 0 {
			for _, unit := range buildCycleUDPUnits(plan, nextSequence) {
				identity := scanCycleUnitIdentity(unit)
				if _, exists := newIdentities[identity]; exists {
					continue
				}
				exists, err := scanCycleUnitIdentityExists(ctx, tx, cycleID, identity)
				if err != nil {
					return false, err
				}
				if exists {
					continue
				}
				added = append(added, unit)
				newIdentities[identity] = struct{}{}
			}
		}
	}

	stamp := sqliteTimestamp(time.Now())
	for _, row := range pending {
		if _, err := tx.ExecContext(ctx, `INSERT OR IGNORE INTO scan_cycle_discovery_checkpoints(cycle_id,sequence,processed_at) VALUES(?,?,?)`, cycleID, row.sequence, stamp); err != nil {
			return false, err
		}
	}
	var addedProbes int64
	for _, unit := range added {
		raw, err := json.Marshal(unit)
		if err != nil {
			return false, err
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO scan_cycle_units(cycle_id,sequence,work_unit_json,identity,phase,probes,status,attempts,snapshot_json,started_at,finished_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`, cycleID, unit.Sequence, raw, scanCycleUnitIdentity(unit), unit.Phase, unit.Probes, "pending", 0, []byte(`{}`), "", "", ""); err != nil {
			return false, err
		}
		addedProbes += unit.Probes
	}
	if len(added) > 0 {
		result, err := tx.ExecContext(ctx, `UPDATE scan_cycles SET total_units=total_units+?,total_probes=total_probes+?,updated_at=? WHERE id=? AND status IN ('running','paused','stalled')`, len(added), addedProbes, stamp, cycleID)
		if err != nil {
			return false, err
		}
		if count, _ := result.RowsAffected(); count != 1 {
			return false, ErrCycleNotResumable
		}
	}
	worked := len(pending) > 0 || len(added) > 0
	if err := tx.Commit(); err != nil {
		return false, err
	}
	return worked, nil
}

// expectedTCPPortsTx returns, per effective address, every positive TCP port
// the job's runtime state currently tracks: baseline ports, and the ports of
// open incidents, pending changes and suppressed changes that expect the port
// to be open. Baseline units and changes name a logical target, so targets
// maps a DNS or other logical name to the addresses pinned by the cycle plan.
func expectedTCPPortsTx(ctx context.Context, tx *sql.Tx, jobID string, targets []scanner.ResolvedTarget) (map[string]map[int]struct{}, error) {
	expected := map[string]map[int]struct{}{}
	if strings.TrimSpace(jobID) == "" {
		return expected, nil
	}
	var raw []byte
	if err := tx.QueryRowContext(ctx, `SELECT state_json FROM job_runtime WHERE job_id=?`, jobID).Scan(&raw); errors.Is(err, sql.ErrNoRows) {
		return expected, nil
	} else if err != nil {
		return expected, err
	}
	var state model.JobState
	if err := json.Unmarshal(raw, &state); err != nil {
		// Legacy or corrupt runtime state cannot safely add expected-port work;
		// keep the empty map and let the discovery evidence stand on its own.
		state = model.JobState{}
	}
	targetAddresses := make(map[string][]string, len(targets))
	for _, target := range targets {
		targetAddresses[target.Name] = append(targetAddresses[target.Name], target.Addresses...)
	}
	addTrackedChangeTCPPorts(expected, state, targetAddresses)
	if state.Baseline == nil {
		return expected, nil
	}
	for _, unit := range state.Baseline.Units {
		if !strings.EqualFold(unit.Protocol, "tcp") {
			continue
		}
		var ports []int
		for _, port := range unit.Ports {
			if port.Port >= 1 && port.Port <= 65535 && isPositiveCyclePortState(port.State) {
				ports = append(ports, port.Port)
			}
		}
		if len(ports) == 0 {
			continue
		}
		// A unit stores the addresses its target resolved to when the baseline
		// was scanned, and a legacy unit stores none. A DNS target can resolve
		// elsewhere by now, so its ports are also expected on every address the
		// plan pinned for the target. The caller drops addresses outside the
		// current discovery batch.
		addresses := append(append([]string(nil), unit.Addresses...), targetAddresses[unit.Target]...)
		if len(addresses) == 0 {
			addresses = []string{unit.Target}
		}
		for _, address := range addresses {
			address = normalizeCycleAddress(address)
			if address == "" {
				address = normalizeCycleAddress(unit.Target)
			}
			if address == "" {
				continue
			}
			expectTCPPorts(expected, address, ports...)
		}
	}
	return expected, nil
}

// addTrackedChangeTCPPorts adds the TCP ports that open incidents, pending
// changes and suppressed changes expect to be open. A change carries only its
// logical target, so each target maps to every address the plan pinned for it;
// a target missing from the plan is used only when it is an address itself.
func addTrackedChangeTCPPorts(expected map[string]map[int]struct{}, state model.JobState, targetAddresses map[string][]string) {
	add := func(change model.Change) {
		if !strings.EqualFold(change.Protocol, "tcp") || change.Port < 1 || change.Port > 65535 || !changeExpectsOpenPort(change) {
			return
		}
		addresses := targetAddresses[change.Target]
		if len(addresses) == 0 {
			addresses = []string{change.Target}
		}
		for _, address := range addresses {
			if address = normalizeCycleAddress(address); address != "" {
				expectTCPPorts(expected, address, change.Port)
			}
		}
	}
	for _, incident := range state.Incidents {
		add(incident.Change)
	}
	for _, pending := range state.Pending {
		add(pending.Change)
	}
	for _, change := range state.SuppressedChanges {
		add(change)
	}
}

func expectTCPPorts(expected map[string]map[int]struct{}, address string, ports ...int) {
	set := expected[address]
	if set == nil {
		set = map[int]struct{}{}
		expected[address] = set
	}
	for _, port := range ports {
		set[port] = struct{}{}
	}
}

func isPositiveCyclePortState(state string) bool {
	state = strings.ToLower(strings.TrimSpace(state))
	return state == "open" || state == "open|filtered"
}

// changeExpectsOpenPort reports whether a tracked change claims its port is
// currently open: a port change to a positive state, on the target or on one
// of its addresses, or a service change whose new value is a fingerprint
// rather than the absence of the port.
func changeExpectsOpenPort(change model.Change) bool {
	switch change.Kind {
	case "port", "port-address":
		return isPositiveCyclePortState(change.New)
	case "service":
		value := strings.TrimSpace(change.New)
		return value != "" && value != "not-open"
	default:
		return false
	}
}

func scanCycleUnitIdentity(unit scanner.WorkUnit) string {
	addresses := append([]string(nil), unit.Addresses...)
	sort.Strings(addresses)
	return unit.Engine + "\x00" + unit.Phase + "\x00" + unit.Protocol + "\x00" + fmt.Sprint(unit.Family) + "\x00" + unit.Ports + "\x00" + strings.Join(addresses, ",")
}

func scanCycleUnitIdentityExists(ctx context.Context, tx *sql.Tx, cycleID, identity string) (bool, error) {
	var exists int
	err := tx.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM scan_cycle_units WHERE cycle_id=? AND identity=?)`, cycleID, identity).Scan(&exists)
	return exists != 0, err
}

func normalizeCycleAddress(raw string) string {
	if ip := net.ParseIP(strings.TrimSpace(raw)); ip != nil {
		return ip.String()
	}
	return ""
}

func formatCyclePorts(ports []int) string {
	if len(ports) == 0 {
		return ""
	}
	sort.Ints(ports)
	parts := make([]string, 0, len(ports))
	start, previous := ports[0], ports[0]
	flush := func() {
		if start == previous {
			parts = append(parts, fmt.Sprint(start))
		} else {
			parts = append(parts, fmt.Sprintf("%d-%d", start, previous))
		}
	}
	for _, port := range ports[1:] {
		if port == previous+1 {
			previous = port
			continue
		}
		flush()
		start, previous = port, port
	}
	flush()
	return strings.Join(parts, ",")
}

func boolFactor(serviceDetection bool) int64 {
	if serviceDetection {
		return 2
	}
	return 1
}

func subsetCycleTargets(targets []scanner.ResolvedTarget, addresses []string) []scanner.ResolvedTarget {
	set := make(map[string]struct{}, len(addresses))
	for _, address := range addresses {
		if normalized := normalizeCycleAddress(address); normalized != "" {
			set[normalized] = struct{}{}
		}
	}
	var out []scanner.ResolvedTarget
	for _, target := range targets {
		selected := make([]string, 0, len(target.Addresses))
		for _, address := range target.Addresses {
			if normalized := normalizeCycleAddress(address); normalized != "" {
				if _, ok := set[normalized]; ok {
					selected = append(selected, normalized)
				}
			}
		}
		if len(selected) == 0 {
			continue
		}
		sort.Strings(selected)
		out = append(out, scanner.ResolvedTarget{Name: target.Name, ConfiguredTarget: target.ConfiguredTarget, Addresses: selected, Aggregate: target.Aggregate, Hostname: target.Hostname})
	}
	return out
}

func buildCycleUDPUnits(plan scanner.WorkPlan, sequence int) []scanner.WorkUnit {
	if plan.Job.UDP == nil {
		return nil
	}
	ports, err := config.ParsePorts(plan.Job.UDP.Ports)
	if err != nil || len(ports) == 0 {
		return nil
	}
	byFamily := map[int][]string{4: {}, 6: {}}
	seen := map[string]struct{}{}
	for _, target := range plan.Targets {
		for _, raw := range target.Addresses {
			address := normalizeCycleAddress(raw)
			if address == "" {
				continue
			}
			if _, exists := seen[address]; exists {
				continue
			}
			seen[address] = struct{}{}
			family := 4
			if net.ParseIP(address).To4() == nil {
				family = 6
			}
			byFamily[family] = append(byFamily[family], address)
		}
	}
	var out []scanner.WorkUnit
	for _, family := range []int{4, 6} {
		addresses := byFamily[family]
		sort.Strings(addresses)
		for start := 0; start < len(addresses); start += 128 {
			end := start + 128
			if end > len(addresses) {
				end = len(addresses)
			}
			batch := append([]string(nil), addresses[start:end]...)
			factor := boolFactor(plan.Job.UDP.ServiceDetection)
			perChunk := 4096
			if capacity := int(65536 / (int64(len(batch)) * factor)); capacity > 0 && perChunk > capacity {
				perChunk = capacity
			}
			if perChunk < 1 {
				perChunk = 1
			}
			for portStart := 0; portStart < len(ports); portStart += perChunk {
				portEnd := portStart + perChunk
				if portEnd > len(ports) {
					portEnd = len(ports)
				}
				chunk := append([]int(nil), ports[portStart:portEnd]...)
				out = append(out, scanner.WorkUnit{Sequence: sequence, Engine: config.EngineNmap, Phase: "udp", Protocol: "udp", Family: family, Targets: subsetCycleTargets(plan.Targets, batch), Addresses: batch, Ports: formatCyclePorts(chunk), PortCount: len(chunk), Probes: int64(len(batch)) * int64(len(chunk)) * factor})
				sequence++
			}
		}
	}
	return out
}

// cyclePlanPrefix is how much of plan_json a cycle read takes. The plan's job
// comes first and fits in it, unless the job lists a very long target list;
// the read then takes all of plan_json.
const cyclePlanPrefix = 256 << 10

// scanCycleColumns are the columns of a scan_cycles row aliased c that
// scanScanCycle reads: of plan_json only its first cyclePlanPrefix bytes.
var scanCycleColumns = `c.id,c.job_id,c.job,c.job_revision,c.config_hash,c.execution_hash,c.baseline_epoch,substr(c.plan_json,1,` + strconv.Itoa(cyclePlanPrefix) + `),c.status,c.attempt_count,c.no_progress_attempts,c.total_units,c.completed_units,c.total_probes,c.completed_probes,c.started_at,c.updated_at,c.expires_at,c.finished_at,c.last_error`

// scanScanCycle reads the scanCycleColumns of the cycle with the given ID
// from row. A missing row is ErrNoScanCycle. When the plan's job does not fit
// in the prefix of plan_json that the row holds, fullPlan reads all of it.
func scanScanCycle(row *sql.Row, id string, fullPlan func() ([]byte, error)) (ScanCycleRecord, error) {
	var cycle ScanCycleRecord
	var planJSON []byte
	var started, updated, expires, finished string
	err := row.Scan(&cycle.ID, &cycle.JobID, &cycle.Job, &cycle.JobRevision, &cycle.ConfigHash, &cycle.ExecutionHash, &cycle.BaselineEpoch, &planJSON, &cycle.Status, &cycle.AttemptCount, &cycle.NoProgressAttempts, &cycle.TotalUnits, &cycle.CompletedUnits, &cycle.TotalProbes, &cycle.CompletedProbes, &started, &updated, &expires, &finished, &cycle.LastError)
	if errors.Is(err, sql.ErrNoRows) {
		return cycle, fmt.Errorf("%w: %s", ErrNoScanCycle, id)
	}
	if err != nil {
		return cycle, err
	}
	if cycle.Plan, err = decodeCyclePlanHeader(planJSON); err != nil && len(planJSON) >= cyclePlanPrefix {
		if planJSON, err = fullPlan(); err == nil {
			cycle.Plan, err = decodeCyclePlanHeader(planJSON)
		}
	}
	if err != nil {
		return cycle, err
	}
	// scan_cycle_units is the authoritative source for dynamically generated
	// enrichment/UDP work. Keep the plan's aggregate counters aligned with the
	// durable cycle columns even when a newer reconciliation intentionally
	// avoids rewriting the large plan_json blob.
	cycle.Plan.TotalUnits = cycle.TotalUnits
	cycle.Plan.TotalProbes = cycle.TotalProbes
	cycle.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
	cycle.UpdatedAt, _ = time.Parse(time.RFC3339Nano, updated)
	cycle.ExpiresAt, _ = time.Parse(time.RFC3339Nano, expires)
	cycle.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
	return cycle, nil
}

// decodeCyclePlanHeader decodes the created_at and job members of a cycle's
// plan_json, which json.Marshal of a scanner.WorkPlan writes before the
// members that grow with the scope, and stops there. Every cycle read, after
// each completed unit too, then costs the same whatever the cycle's scope.
func decodeCyclePlanHeader(raw []byte) (scanner.WorkPlan, error) {
	var plan scanner.WorkPlan
	decoder := json.NewDecoder(bytes.NewReader(raw))
	if token, err := decoder.Token(); err != nil || token != json.Delim('{') {
		return plan, fmt.Errorf("decode scan cycle plan: not a JSON object")
	}
	for found := 0; found < 2 && decoder.More(); {
		token, err := decoder.Token()
		if err != nil {
			return plan, fmt.Errorf("decode scan cycle plan: %w", err)
		}
		var value any = &skippedJSON{}
		switch token {
		case "created_at":
			value, found = &plan.CreatedAt, found+1
		case "job":
			value, found = &plan.Job, found+1
		}
		if err := decoder.Decode(value); err != nil {
			return plan, fmt.Errorf("decode scan cycle plan: %w", err)
		}
	}
	return plan, nil
}

// skippedJSON discards a JSON value.
type skippedJSON struct{}

func (*skippedJSON) UnmarshalJSON([]byte) error { return nil }

// storedWorkPlan decodes a plan_json without its units, which cycles created
// before the units were left out of it still hold.
type storedWorkPlan struct {
	scanner.WorkPlan
	Units skippedJSON `json:"units"`
}

// scanCyclePlan returns the complete plan of a cycle of any tenant, without
// its units, with the totals of the cycle's durable columns.
func (ss *SystemStore) scanCyclePlan(ctx context.Context, id string) (scanner.WorkPlan, error) {
	var raw []byte
	var plan storedWorkPlan
	err := ss.store.reader().QueryRowContext(ctx, `SELECT plan_json,total_units,total_probes FROM scan_cycles WHERE id=?`, id).Scan(&raw, &plan.TotalUnits, &plan.TotalProbes)
	if errors.Is(err, sql.ErrNoRows) {
		return scanner.WorkPlan{}, fmt.Errorf("%w: %s", ErrNoScanCycle, id)
	}
	if err != nil {
		return scanner.WorkPlan{}, err
	}
	totalUnits, totalProbes := plan.TotalUnits, plan.TotalProbes
	if err := json.Unmarshal(raw, &plan); err != nil {
		return scanner.WorkPlan{}, err
	}
	plan.TotalUnits, plan.TotalProbes = totalUnits, totalProbes
	return plan.WorkPlan, nil
}

// GetScanCycle returns one of the tenant's cycles with its pinned plan. A
// cycle belongs to the tenant of its job; a cycle of another tenant is
// ErrNoScanCycle, like an unknown ID.
func (ts *TenantStore) GetScanCycle(ctx context.Context, id string) (ScanCycleRecord, error) {
	if err := ts.ready(); err != nil {
		return ScanCycleRecord{}, err
	}
	return scanScanCycle(ts.store.reader().QueryRowContext(ctx, `SELECT `+scanCycleColumns+` FROM scan_cycles c JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE c.id=?`, ts.scope.id, id), id, func() ([]byte, error) {
		var raw []byte
		err := ts.store.reader().QueryRowContext(ctx, `SELECT c.plan_json FROM scan_cycles c JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE c.id=?`, ts.scope.id, id).Scan(&raw)
		return raw, err
	})
}

// scanCycle returns a cycle of any tenant. The daemon's lifecycle writers
// use it to return the cycle they changed.
func (ss *SystemStore) scanCycle(ctx context.Context, id string) (ScanCycleRecord, error) {
	return scanScanCycle(ss.store.reader().QueryRowContext(ctx, `SELECT `+scanCycleColumns+` FROM scan_cycles c WHERE c.id=?`, id), id, func() ([]byte, error) {
		var raw []byte
		err := ss.store.reader().QueryRowContext(ctx, `SELECT plan_json FROM scan_cycles WHERE id=?`, id).Scan(&raw)
		return raw, err
	})
}

// ScanCycleProbeTotals reports the durable execution categories for one of
// the tenant's resumable cycles without decoding checkpoint payloads; a
// cycle of another tenant has no probes. Naabu discovery and Nmap
// enrichment/UDP work use separate deployment budgets; keeping this
// aggregate query set-based lets the application reject an expansion before
// starting another scanner process.
func (ts *TenantStore) ScanCycleProbeTotals(ctx context.Context, cycleID string) (discovery, nmap int64, err error) {
	if err := ts.ready(); err != nil {
		return 0, 0, err
	}
	err = ts.store.reader().QueryRowContext(ctx, `
		SELECT
		COALESCE(SUM(CASE WHEN u.phase='discovery' THEN u.probes ELSE 0 END),0),
		COALESCE(SUM(CASE WHEN u.phase<>'discovery' THEN u.probes ELSE 0 END),0)
		FROM scan_cycle_units u JOIN scan_cycles c ON c.id=u.cycle_id JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE u.cycle_id=?`, ts.scope.id, cycleID).Scan(&discovery, &nmap)
	return discovery, nmap, err
}

// GetActiveScanCycle returns the running, paused, or stalled cycle of one of
// the tenant's jobs. A job of another tenant has none: ErrNoScanCycle.
func (ts *TenantStore) GetActiveScanCycle(ctx context.Context, jobID string) (ScanCycleRecord, error) {
	if err := ts.ready(); err != nil {
		return ScanCycleRecord{}, err
	}
	var id string
	err := ts.store.reader().QueryRowContext(ctx, `SELECT c.id FROM scan_cycles c JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE c.job_id=? AND c.status IN ('running','paused','stalled') ORDER BY c.started_at DESC LIMIT 1`, ts.scope.id, jobID).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return ScanCycleRecord{}, ErrNoScanCycle
	}
	if err != nil {
		return ScanCycleRecord{}, err
	}
	return ts.GetScanCycle(ctx, id)
}

// ListActiveScanCycleSummaries returns the current active cycle for each of
// the tenant's visible jobs in one query. The partial unique index on
// scan_cycles guarantees at most one running, paused, or stalled cycle per
// job.
func (ts *TenantStore) ListActiveScanCycleSummaries(ctx context.Context, includeArchived bool) (map[string]ScanCycleSummary, error) {
	if err := ts.ready(); err != nil {
		return nil, err
	}
	rows, err := ts.store.reader().QueryContext(ctx, `SELECT c.id,c.job_id,c.job_revision,c.status,c.attempt_count,c.no_progress_attempts,c.total_units,c.completed_units,c.total_probes,c.completed_probes,c.started_at,c.updated_at,c.expires_at,c.finished_at,c.last_error
 FROM scan_cycles c JOIN jobs j ON j.id=c.job_id AND j.tenant_id=?
 WHERE c.status IN ('running','paused','stalled') AND (?=1 OR j.archived=0)`, ts.scope.id, boolInt(includeArchived))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := make(map[string]ScanCycleSummary)
	for rows.Next() {
		var cycle ScanCycleSummary
		var started, updated, expires, finished string
		if err := rows.Scan(&cycle.ID, &cycle.JobID, &cycle.JobRevision, &cycle.Status, &cycle.AttemptCount, &cycle.NoProgressAttempts, &cycle.TotalUnits, &cycle.CompletedUnits, &cycle.TotalProbes, &cycle.CompletedProbes, &started, &updated, &expires, &finished, &cycle.LastError); err != nil {
			return nil, err
		}
		cycle.StartedAt, cycle.UpdatedAt, cycle.ExpiresAt, cycle.FinishedAt = scanTime(started), scanTime(updated), scanTime(expires), scanTime(finished)
		out[cycle.JobID] = cycle
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

// GetLatestScanCycle returns the newest cycle for one of the tenant's jobs
// regardless of its terminal state; a job of another tenant has none. It is
// intentionally separate from GetActiveScanCycle: a completed, discarded, or
// expired cycle must remain visible in history but must never block
// creation of a fresh cycle.
func (ts *TenantStore) GetLatestScanCycle(ctx context.Context, jobID string) (ScanCycleRecord, error) {
	if err := ts.ready(); err != nil {
		return ScanCycleRecord{}, err
	}
	var id string
	err := ts.store.reader().QueryRowContext(ctx, `SELECT c.id FROM scan_cycles c JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE c.job_id=? ORDER BY c.started_at DESC,c.id DESC LIMIT 1`, ts.scope.id, jobID).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return ScanCycleRecord{}, ErrNoScanCycle
	}
	if err != nil {
		return ScanCycleRecord{}, err
	}
	return ts.GetScanCycle(ctx, id)
}

// GetRecoverableScanCycle returns an active cycle or a completed cycle whose
// final scan was not promoted, for one of the tenant's jobs. The latter is
// the narrow crash-recovery window between marking a cycle complete and
// committing its immutable scan record.
func (ts *TenantStore) GetRecoverableScanCycle(ctx context.Context, jobID string) (ScanCycleRecord, error) {
	if err := ts.ready(); err != nil {
		return ScanCycleRecord{}, err
	}
	cycle, err := ts.GetActiveScanCycle(ctx, jobID)
	if err == nil {
		return cycle, nil
	}
	if !errors.Is(err, ErrNoScanCycle) {
		return ScanCycleRecord{}, err
	}
	cycle, err = ts.GetLatestScanCycle(ctx, jobID)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	if cycle.Status != "completed" {
		return ScanCycleRecord{}, ErrNoScanCycle
	}
	promoted, err := ts.ScanCycleHasScan(ctx, cycle.ID)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	if promoted {
		return ScanCycleRecord{}, ErrNoScanCycle
	}
	return cycle, nil
}

// ScanCycleExpiryNotified reports whether one of the tenant's expired cycles
// already produced its terminal scan record; only the tenant's scans count.
// Housekeeping can expire a cycle between schedule ticks; keeping this check
// separate lets the next trigger emit exactly one failure notification
// before a subsequent trigger starts a fresh cycle.
func (ts *TenantStore) ScanCycleExpiryNotified(ctx context.Context, cycleID string) (bool, error) {
	if err := ts.ready(); err != nil {
		return false, err
	}
	var count int
	err := ts.store.reader().QueryRowContext(ctx, `SELECT COUNT(*) FROM scans WHERE cycle_id=? AND tenant_id=? AND cycle_status='expired' AND status='timed_out'`, cycleID, ts.scope.id).Scan(&count)
	return count > 0, err
}

// scanCycleHasScanQuery is the production statement explained by the index
// regression test. Keeping the SQL in one place prevents the test from
// drifting away from the query used by the cycle guard. A cycle can have many
// persisted paused/failed attempt rows; only the successful (or incomplete,
// but fully promoted) final record proves that the merged cycle was promoted.
// Its arguments are the cycle ID and the tenant ID: only the tenant's scans
// count.
const scanCycleHasScanQuery = `SELECT COUNT(*) FROM scans WHERE cycle_id=? AND tenant_id=? AND cycle_status='completed' AND status IN ('success','incomplete')`

// ScanCycleHasScan reports whether one of the tenant's terminal cycles has
// already been promoted into scan history; a cycle of another tenant has
// not. The cycle is marked completed before the engine's final transaction,
// so a process crash in that small window must be recoverable on the next
// trigger rather than silently starting a brand-new cycle.
func (ts *TenantStore) ScanCycleHasScan(ctx context.Context, cycleID string) (bool, error) {
	if err := ts.ready(); err != nil {
		return false, err
	}
	var count int
	if err := ts.store.reader().QueryRowContext(ctx, scanCycleHasScanQuery, cycleID, ts.scope.id).Scan(&count); err != nil {
		return false, err
	}
	return count > 0, nil
}

// ListScanCycleUnitSummaries returns the progress of every unit of one of
// the tenant's cycles, in order; a cycle of another tenant has none.
func (ts *TenantStore) ListScanCycleUnitSummaries(ctx context.Context, cycleID string) ([]ScanCycleUnitSummary, error) {
	if err := ts.ready(); err != nil {
		return nil, err
	}
	rows, err := ts.store.reader().QueryContext(ctx, `SELECT u.cycle_id,u.sequence,u.work_unit_json,u.status,u.attempts,u.failures,u.started_at,u.finished_at,u.last_error FROM scan_cycle_units u JOIN scan_cycles c ON c.id=u.cycle_id JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE u.cycle_id=? ORDER BY u.sequence`, ts.scope.id, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []ScanCycleUnitSummary
	for rows.Next() {
		var item ScanCycleUnitSummary
		var raw []byte
		var started, finished string
		if err := rows.Scan(&item.CycleID, &item.Sequence, &raw, &item.Status, &item.Attempts, &item.Failures, &started, &finished, &item.LastError); err != nil {
			return nil, err
		}
		var unit scanner.WorkUnit
		if err := json.Unmarshal(raw, &unit); err != nil {
			return nil, err
		}
		item.Engine, item.Phase = unit.Engine, unit.Phase
		item.Protocol, item.Family, item.Ports, item.PortCount, item.Addresses, item.Probes = unit.Protocol, unit.Family, unit.Ports, unit.PortCount, len(unit.Addresses), unit.Probes
		item.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
		item.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
		out = append(out, item)
	}
	return out, rows.Err()
}

// ListScanCycleUnitSummariesPage returns a bounded progress page of one of
// the tenant's cycles; a cycle of another tenant has an empty page. Cycle
// plans can contain one unit per address/port batch, so exposing the entire
// list in one response lets a broad scan turn a status request into an
// unbounded read. Keep the legacy unpaged method above for internal callers
// and compatibility, while the HTTP endpoint uses this bounded projection.
func (ts *TenantStore) ListScanCycleUnitSummariesPage(ctx context.Context, cycleID string, limit, offset int) (Page[ScanCycleUnitSummary], error) {
	if err := ts.ready(); err != nil {
		return Page[ScanCycleUnitSummary]{}, err
	}
	limit, offset = normalizePage(limit, offset)
	var page Page[ScanCycleUnitSummary]
	readDB := ts.store.reader()
	if err := readDB.QueryRowContext(ctx, `SELECT COUNT(*) FROM scan_cycle_units u JOIN scan_cycles c ON c.id=u.cycle_id JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE u.cycle_id=?`, ts.scope.id, cycleID).Scan(&page.Total); err != nil {
		return page, err
	}
	rows, err := readDB.QueryContext(ctx, `SELECT u.cycle_id,u.sequence,u.work_unit_json,u.status,u.attempts,u.failures,u.started_at,u.finished_at,u.last_error FROM scan_cycle_units u JOIN scan_cycles c ON c.id=u.cycle_id JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE u.cycle_id=? ORDER BY u.sequence LIMIT ? OFFSET ?`, ts.scope.id, cycleID, limit, offset)
	if err != nil {
		return page, err
	}
	defer rows.Close()
	for rows.Next() {
		var item ScanCycleUnitSummary
		var raw []byte
		var started, finished string
		if err := rows.Scan(&item.CycleID, &item.Sequence, &raw, &item.Status, &item.Attempts, &item.Failures, &started, &finished, &item.LastError); err != nil {
			return page, err
		}
		var unit scanner.WorkUnit
		if err := json.Unmarshal(raw, &unit); err != nil {
			return page, err
		}
		item.Engine, item.Phase = unit.Engine, unit.Phase
		item.Protocol, item.Family, item.Ports, item.PortCount, item.Addresses, item.Probes = unit.Protocol, unit.Family, unit.Ports, unit.PortCount, len(unit.Addresses), unit.Probes
		item.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
		item.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
		page.Items = append(page.Items, item)
	}
	return page, rows.Err()
}

// StartScanCycleAttempt resets a unit left running by a process crash and
// atomically marks the cycle running for this attempt.
func (ss *SystemStore) StartScanCycleAttempt(ctx context.Context, id string) (ScanCycleRecord, error) {
	now := time.Now().UTC()
	tx, err := ss.store.DB.BeginTx(ctx, nil)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	defer tx.Rollback()
	var status, expires string
	if err = tx.QueryRowContext(ctx, `SELECT status,expires_at FROM scan_cycles WHERE id=?`, id).Scan(&status, &expires); errors.Is(err, sql.ErrNoRows) {
		return ScanCycleRecord{}, fmt.Errorf("%w: %s", ErrNoScanCycle, id)
	} else if err != nil {
		return ScanCycleRecord{}, err
	}
	if status != "paused" && status != "stalled" && status != "running" {
		return ScanCycleRecord{}, ErrCycleNotResumable
	}
	if expiry, parseErr := time.Parse(time.RFC3339Nano, expires); parseErr == nil && !expiry.IsZero() && !now.Before(expiry) {
		stamp := sqliteTimestamp(now)
		transition, transitionErr := tx.ExecContext(ctx, `UPDATE scan_cycles SET status='expired',updated_at=?,finished_at=?,last_error='scan cycle exceeded its resume window' WHERE id=? AND status IN ('running','paused','stalled')`, stamp, stamp, id)
		if transitionErr != nil {
			return ScanCycleRecord{}, transitionErr
		}
		changed, _ := transition.RowsAffected()
		if changed != 1 {
			// Another writer may have completed, discarded, or expired the cycle
			// after our initial read. Do not clear its checkpoints in that case;
			// the terminal transition (and any cleanup) belongs to that writer.
			return ScanCycleRecord{}, ErrCycleNotResumable
		}
		// Commit the terminal transition before clearing checkpoint payloads. The
		// cleanup is deliberately performed in bounded follow-up transactions so a
		// full-range cycle cannot hold the writer while every unit is rewritten.
		// Without committing first, the deferred rollback would undo expiry and the
		// next trigger could rediscover the same cycle as resumable.
		if err = tx.Commit(); err != nil {
			return ScanCycleRecord{}, err
		}
		// Cleanup is best effort here: the terminal state is already durable and
		// the regular retention pass empties any payloads of an expired cycle
		// left behind by a canceled context or a transient database error.
		_ = ss.clearExpiredCyclePayloads(ctx, []string{id})
		return ScanCycleRecord{}, ErrCycleNotResumable
	}
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycle_units SET status='pending',started_at='',last_error=last_error WHERE cycle_id=? AND status='running'`, id); err != nil {
		return ScanCycleRecord{}, err
	}
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycles SET status='running',attempt_count=attempt_count+1,updated_at=? WHERE id=? AND status IN ('paused','stalled','running')`, sqliteTimestamp(now), id); err != nil {
		return ScanCycleRecord{}, err
	}
	if err = tx.Commit(); err != nil {
		return ScanCycleRecord{}, err
	}
	return ss.scanCycle(ctx, id)
}

// NextScanCycleUnit returns the first pending unit of a running cycle.
func (ss *SystemStore) NextScanCycleUnit(ctx context.Context, cycleID string) (ScanCycleUnit, error) {
	var unit ScanCycleUnit
	var raw, snapshot []byte
	var started, finished string
	status, statusErr := ss.scanCycleStatus(ctx, cycleID)
	if statusErr != nil {
		return unit, statusErr
	}
	if status != "running" {
		if status == "completed" {
			return unit, ErrNoPendingUnit
		}
		return unit, ErrCycleNotResumable
	}
	err := ss.store.reader().QueryRowContext(ctx, `SELECT cycle_id,sequence,work_unit_json,status,attempts,failures,snapshot_json,started_at,finished_at,last_error FROM scan_cycle_units WHERE cycle_id=? AND status='pending' ORDER BY sequence LIMIT 1`, cycleID).
		Scan(&unit.CycleID, &unit.Sequence, &raw, &unit.Status, &unit.Attempts, &unit.Failures, &snapshot, &started, &finished, &unit.LastError)
	if errors.Is(err, sql.ErrNoRows) {
		return unit, ErrNoPendingUnit
	}
	if err != nil {
		return unit, err
	}
	if err = json.Unmarshal(raw, &unit.Unit); err != nil {
		return unit, err
	}
	if len(snapshot) > 0 && string(snapshot) != "{}" && string(snapshot) != "null" {
		if err = json.Unmarshal(snapshot, &unit.Snapshot); err != nil {
			return unit, err
		}
	}
	unit.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
	unit.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
	return unit, nil
}

// ClaimScanCycleUnit marks a pending unit of a running cycle as running
// while the cycle is inside its resume window.
func (ss *SystemStore) ClaimScanCycleUnit(ctx context.Context, cycleID string, sequence int) (ScanCycleUnit, error) {
	now := time.Now().UTC()
	nowText := sqliteTimestamp(now)
	result, err := ss.store.DB.ExecContext(ctx, `UPDATE scan_cycle_units SET status='running',attempts=attempts+1,started_at=?,last_error='' WHERE cycle_id=? AND sequence=? AND status='pending' AND EXISTS (SELECT 1 FROM scan_cycles WHERE id=? AND status='running' AND (expires_at='' OR expires_at>?))`, nowText, cycleID, sequence, cycleID, nowText)
	if err != nil {
		return ScanCycleUnit{}, err
	}
	if count, _ := result.RowsAffected(); count != 1 {
		if status, statusErr := ss.scanCycleStatus(ctx, cycleID); statusErr != nil {
			return ScanCycleUnit{}, statusErr
		} else if status != "running" {
			return ScanCycleUnit{}, ErrCycleNotResumable
		}
		// A deadline can pass between NextScanCycleUnit and the atomic claim.
		// Expire it before reporting the refusal so a retry cannot consume an
		// attempt budget after the resume window has closed. The claiming
		// scan holds its job's lease, which ExpireScanCycles respects, so the
		// cycle is expired on its own, as the scan's start does.
		var expires string
		if expiryErr := ss.store.reader().QueryRowContext(ctx, `SELECT expires_at FROM scan_cycles WHERE id=? AND status='running'`, cycleID).Scan(&expires); expiryErr == nil {
			if deadline, parseErr := time.Parse(time.RFC3339Nano, expires); parseErr == nil && !deadline.IsZero() && !now.Before(deadline) {
				_, _ = ss.ExpireScanCycle(ctx, cycleID, now)
				return ScanCycleUnit{}, ErrCycleNotResumable
			}
		}
		return ScanCycleUnit{}, ErrNoPendingUnit
	}
	return ss.getScanCycleUnit(ctx, cycleID, sequence)
}

func (ss *SystemStore) scanCycleStatus(ctx context.Context, cycleID string) (string, error) {
	var status string
	err := ss.store.reader().QueryRowContext(ctx, `SELECT status FROM scan_cycles WHERE id=?`, cycleID).Scan(&status)
	if errors.Is(err, sql.ErrNoRows) {
		return "", fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
	}
	return status, err
}

func (ss *SystemStore) getScanCycleUnit(ctx context.Context, cycleID string, sequence int) (ScanCycleUnit, error) {
	var unit ScanCycleUnit
	var raw, snapshot []byte
	var started, finished string
	err := ss.store.reader().QueryRowContext(ctx, `SELECT cycle_id,sequence,work_unit_json,status,attempts,failures,snapshot_json,started_at,finished_at,last_error FROM scan_cycle_units WHERE cycle_id=? AND sequence=?`, cycleID, sequence).
		Scan(&unit.CycleID, &unit.Sequence, &raw, &unit.Status, &unit.Attempts, &unit.Failures, &snapshot, &started, &finished, &unit.LastError)
	if err != nil {
		return unit, err
	}
	if err = json.Unmarshal(raw, &unit.Unit); err != nil {
		return unit, err
	}
	if len(snapshot) > 0 && string(snapshot) != "{}" && string(snapshot) != "null" {
		_ = json.Unmarshal(snapshot, &unit.Snapshot)
	}
	unit.StartedAt, _ = time.Parse(time.RFC3339Nano, started)
	unit.FinishedAt, _ = time.Parse(time.RFC3339Nano, finished)
	return unit, nil
}

// CompleteScanCycleUnit stores the checkpoint of a running unit and counts
// its progress on the running cycle.
func (ss *SystemStore) CompleteScanCycleUnit(ctx context.Context, cycleID string, sequence int, snapshot model.Snapshot) error {
	raw, err := json.Marshal(snapshot)
	if err != nil {
		return err
	}
	now := time.Now().UTC()
	tx, err := ss.store.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var status string
	var unitRaw []byte
	if err = tx.QueryRowContext(ctx, `SELECT status,work_unit_json FROM scan_cycle_units WHERE cycle_id=? AND sequence=?`, cycleID, sequence).Scan(&status, &unitRaw); err != nil {
		return err
	}
	if status == "completed" {
		return nil
	}
	if status != "running" {
		return fmt.Errorf("scan cycle unit %d is not running", sequence)
	}
	var cycleStatus string
	if err = tx.QueryRowContext(ctx, `SELECT status FROM scan_cycles WHERE id=?`, cycleID).Scan(&cycleStatus); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
		}
		return err
	}
	if cycleStatus != "running" {
		return ErrCycleNotResumable
	}
	var unit scanner.WorkUnit
	if err = json.Unmarshal(unitRaw, &unit); err != nil {
		return err
	}
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycle_units SET status='completed',snapshot_json=?,finished_at=?,last_error='' WHERE cycle_id=? AND sequence=?`, raw, sqliteTimestamp(now), cycleID, sequence); err != nil {
		return err
	}
	cycleUpdate, err := tx.ExecContext(ctx, `UPDATE scan_cycles SET completed_units=completed_units+1,completed_probes=completed_probes+?,updated_at=? WHERE id=? AND status='running'`, unit.Probes, sqliteTimestamp(now), cycleID)
	if err != nil {
		return err
	}
	if count, _ := cycleUpdate.RowsAffected(); count != 1 {
		return ErrCycleNotResumable
	}
	return tx.Commit()
}

// RetryScanCycleUnit returns a claimed unit of a running cycle to pending
// without counting a scanner failure.
func (ss *SystemStore) RetryScanCycleUnit(ctx context.Context, cycleID string, sequence int, lastError string) error {
	return ss.retryScanCycleUnit(ctx, cycleID, sequence, lastError, false)
}

// RetryScanCycleUnitAfterFailure returns a claimed unit to pending and records
// one completed retryable scanner failure. Claims and process-recovery counts
// are intentionally kept separate from this counter: a unit can be claimed
// more than once without ever completing a failed execution.
func (ss *SystemStore) RetryScanCycleUnitAfterFailure(ctx context.Context, cycleID string, sequence int, lastError string) error {
	return ss.retryScanCycleUnit(ctx, cycleID, sequence, lastError, true)
}

func (ss *SystemStore) retryScanCycleUnit(ctx context.Context, cycleID string, sequence int, lastError string, countFailure bool) error {
	failureIncrement := 0
	if countFailure {
		failureIncrement = 1
	}
	result, err := ss.store.DB.ExecContext(ctx, `UPDATE scan_cycle_units SET status='pending',failures=failures+?,last_error=? WHERE cycle_id=? AND sequence=? AND status='running' AND EXISTS (SELECT 1 FROM scan_cycles WHERE id=? AND status='running')`, failureIncrement, trimCycleError(lastError), cycleID, sequence, cycleID)
	if err != nil {
		return err
	}
	if count, _ := result.RowsAffected(); count == 1 {
		return nil
	}
	status, statusErr := ss.scanCycleStatus(ctx, cycleID)
	if statusErr != nil {
		return statusErr
	}
	if status != "running" {
		return ErrCycleNotResumable
	}
	return ErrNoPendingUnit
}

// SplitScanCycleUnit replaces a running unit of a running cycle with two
// pending halves: first keeps the unit's sequence and second is appended.
func (ss *SystemStore) SplitScanCycleUnit(ctx context.Context, cycleID string, sequence int, first, second scanner.WorkUnit, lastError string) error {
	firstRaw, err := json.Marshal(first)
	if err != nil {
		return err
	}
	secondRaw, err := json.Marshal(second)
	if err != nil {
		return err
	}
	tx, err := ss.store.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var status string
	var parentAttempts int
	var originalRaw []byte
	if err = tx.QueryRowContext(ctx, `SELECT status,attempts,work_unit_json FROM scan_cycle_units WHERE cycle_id=? AND sequence=?`, cycleID, sequence).Scan(&status, &parentAttempts, &originalRaw); err != nil {
		return err
	}
	if status == "completed" {
		return nil
	}
	if status != "running" {
		return ErrCycleNotResumable
	}
	var cycleStatus string
	if err = tx.QueryRowContext(ctx, `SELECT status FROM scan_cycles WHERE id=?`, cycleID).Scan(&cycleStatus); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
		}
		return err
	}
	if cycleStatus != "running" {
		return ErrCycleNotResumable
	}
	var original scanner.WorkUnit
	if err := json.Unmarshal(originalRaw, &original); err != nil {
		return err
	}
	var next int
	if err = tx.QueryRowContext(ctx, `SELECT COALESCE(MAX(sequence),-1)+1 FROM scan_cycle_units WHERE cycle_id=?`, cycleID).Scan(&next); err != nil {
		return err
	}
	second.Sequence = next
	secondRaw, err = json.Marshal(second)
	if err != nil {
		return err
	}
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycle_units SET work_unit_json=?,identity=?,phase=?,probes=?,status='pending',attempts=?,failures=0,last_error=? WHERE cycle_id=? AND sequence=?`, firstRaw, scanCycleUnitIdentity(first), first.Phase, first.Probes, parentAttempts, trimCycleError(lastError), cycleID, sequence); err != nil {
		return err
	}
	if _, err = tx.ExecContext(ctx, `INSERT INTO scan_cycle_units(cycle_id,sequence,work_unit_json,identity,phase,probes,status,attempts,failures,snapshot_json,started_at,finished_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`, cycleID, next, secondRaw, scanCycleUnitIdentity(second), second.Phase, second.Probes, "pending", parentAttempts, 0, []byte(`{}`), "", "", ""); err != nil {
		return err
	}
	probeDelta := first.Probes + second.Probes - original.Probes
	cycleUpdate, err := tx.ExecContext(ctx, `UPDATE scan_cycles SET total_units=total_units+1,total_probes=total_probes+?,updated_at=?,last_error=? WHERE id=? AND status='running'`, probeDelta, sqliteTimestamp(time.Now()), trimCycleError(lastError), cycleID)
	if err != nil {
		return err
	}
	if count, _ := cycleUpdate.RowsAffected(); count != 1 {
		return ErrCycleNotResumable
	}
	return tx.Commit()
}

// PauseScanCycle pauses an active cycle at the end of an attempt and counts
// an attempt without progress, then returns the cycle.
func (ss *SystemStore) PauseScanCycle(ctx context.Context, cycleID string, noProgress bool, lastError string) (ScanCycleRecord, error) {
	now := sqliteTimestamp(time.Now())
	query := `UPDATE scan_cycles SET status='paused',no_progress_attempts=CASE WHEN ? THEN no_progress_attempts+1 ELSE 0 END,updated_at=?,last_error=? WHERE id=? AND status IN ('running','paused','stalled')`
	if _, err := ss.store.DB.ExecContext(ctx, query, noProgress, now, trimCycleError(lastError), cycleID); err != nil {
		return ScanCycleRecord{}, err
	}
	return ss.scanCycle(ctx, cycleID)
}

// MarkScanCycleStalled marks an active cycle stalled with the error that
// stopped it, then returns the cycle.
func (ss *SystemStore) MarkScanCycleStalled(ctx context.Context, cycleID, lastError string) (ScanCycleRecord, error) {
	if _, err := ss.store.DB.ExecContext(ctx, `UPDATE scan_cycles SET status='stalled',updated_at=?,last_error=? WHERE id=? AND status IN ('running','paused','stalled')`, sqliteTimestamp(time.Now()), trimCycleError(lastError), cycleID); err != nil {
		return ScanCycleRecord{}, err
	}
	return ss.scanCycle(ctx, cycleID)
}

// CompleteScanCycle marks a running cycle whose units are all completed as
// completed, then returns the cycle.
func (ss *SystemStore) CompleteScanCycle(ctx context.Context, cycleID string) (ScanCycleRecord, error) {
	now := sqliteTimestamp(time.Now())
	tx, err := ss.store.DB.BeginTx(ctx, nil)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	defer tx.Rollback()
	var status string
	var completed, total int
	if err = tx.QueryRowContext(ctx, `SELECT status,completed_units,total_units FROM scan_cycles WHERE id=?`, cycleID).Scan(&status, &completed, &total); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ScanCycleRecord{}, fmt.Errorf("%w: %s", ErrNoScanCycle, cycleID)
		}
		return ScanCycleRecord{}, err
	}
	if status == "completed" {
		_ = tx.Rollback()
		return ss.scanCycle(ctx, cycleID)
	}
	if status != "running" {
		return ScanCycleRecord{}, ErrCycleNotResumable
	}
	if completed != total {
		return ScanCycleRecord{}, fmt.Errorf("%w: %d of %d units completed", ErrCycleIncomplete, completed, total)
	}
	// Keep the completed unit payloads until the merged scan is promoted. The
	// promotion is a separate transaction, and retaining this short-lived
	// recovery source means a process crash between these operations cannot lose
	// a completed cycle. SaveScan/FinalizeManagedScan reclaim the payloads after
	// the immutable scan and its indexes are committed.
	if _, err = tx.ExecContext(ctx, `UPDATE scan_cycles SET status='completed',updated_at=?,finished_at=?,last_error='' WHERE id=? AND status='running'`, now, now, cycleID); err != nil {
		return ScanCycleRecord{}, err
	}
	if err = tx.Commit(); err != nil {
		return ScanCycleRecord{}, err
	}
	return ss.scanCycle(ctx, cycleID)
}

// tenantScanCycleSQL selects the ID of one cycle if it belongs to a tenant.
// Its arguments are the tenant ID and the cycle ID.
const tenantScanCycleSQL = `SELECT c.id FROM scan_cycles c JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE c.id=?`

// DiscardScanCycle discards one of the tenant's active cycles, or a
// completed one whose scan was not promoted, and deletes its units. A cycle
// of another tenant is ErrNoScanCycle, like an unknown ID, and is left
// unchanged. A running cycle whose job holds a live lease is refused with
// ErrJobScanActive.
func (ts *TenantStore) DiscardScanCycle(ctx context.Context, cycleID string) error {
	if err := ts.ready(); err != nil {
		return err
	}
	tx, err := ts.store.DB.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var status, jobID string
	if err = tx.QueryRowContext(ctx, `SELECT c.status,c.job_id FROM scan_cycles c JOIN jobs j ON j.id=c.job_id AND j.tenant_id=? WHERE c.id=?`, ts.scope.id, cycleID).Scan(&status, &jobID); errors.Is(err, sql.ErrNoRows) {
		return ErrNoScanCycle
	} else if err != nil {
		return err
	}
	if status != "running" && status != "paused" && status != "stalled" && status != "completed" {
		return ErrCycleNotResumable
	}
	if status == "running" {
		var leased int
		if err := tx.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM job_leases WHERE job=? AND expires_at>?)`, jobID, sqliteTimestamp(time.Now())).Scan(&leased); err != nil {
			return err
		}
		if leased != 0 {
			return ErrJobScanActive
		}
	}
	if status == "completed" {
		var promoted int
		if err := tx.QueryRowContext(ctx, scanCycleHasScanQuery, cycleID, ts.scope.id).Scan(&promoted); err != nil {
			return err
		}
		if promoted > 0 {
			return ErrCycleNotResumable
		}
	}
	stamp := sqliteTimestamp(time.Now())
	result, err := tx.ExecContext(ctx, `UPDATE scan_cycles SET status='discarded',updated_at=?,finished_at=?,last_error='discarded by administrator',completed_units=0,total_units=0,completed_probes=0,total_probes=0 WHERE id=? AND status IN ('running','paused','stalled','completed') AND id IN (`+tenantScanCycleSQL+`)`, stamp, stamp, cycleID, ts.scope.id, cycleID)
	if err != nil {
		return err
	}
	updated, err := result.RowsAffected()
	if err != nil {
		return err
	}
	if updated != 1 {
		return ErrCycleNotResumable
	}
	if _, err = tx.ExecContext(ctx, `DELETE FROM scan_cycle_units WHERE cycle_id=? AND cycle_id IN (`+tenantScanCycleSQL+`)`, cycleID, ts.scope.id, cycleID); err != nil {
		return err
	}
	return tx.Commit()
}

// ExpireScanCycles ends every tenant's active cycles whose resume window has
// elapsed at now, in bounded batches, except those whose job holds a live
// lease, and returns how many it ended.
func (ss *SystemStore) ExpireScanCycles(ctx context.Context, now time.Time) (int64, error) {
	if now.IsZero() {
		now = time.Now().UTC()
	}
	stamp := sqliteTimestamp(now)
	var total int64
	for {
		if err := ctx.Err(); err != nil {
			return total, err
		}
		tx, err := ss.store.DB.BeginTx(ctx, nil)
		if err != nil {
			return total, err
		}
		ids, err := expiredScanCycleIDs(ctx, tx, stamp)
		if err != nil {
			_ = tx.Rollback()
			return total, err
		}
		if len(ids) == 0 {
			if err := tx.Commit(); err != nil {
				return total, err
			}
			return total, nil
		}
		placeholders := make([]string, len(ids))
		args := []any{stamp, stamp}
		for i, id := range ids {
			placeholders[i] = "?"
			args = append(args, id)
		}
		query := `UPDATE scan_cycles SET status='expired',updated_at=?,finished_at=?,last_error='scan cycle exceeded its resume window' WHERE status IN ('running','paused','stalled') AND id IN (` + strings.Join(placeholders, ",") + `)`
		result, err := tx.ExecContext(ctx, query, args...)
		if err != nil {
			_ = tx.Rollback()
			return total, err
		}
		changed, _ := result.RowsAffected()
		if err := tx.Commit(); err != nil {
			return total, err
		}
		total += changed
		if err := ss.clearExpiredCyclePayloads(ctx, ids); err != nil {
			return total, err
		}
	}
}

// ExpireScanCycle ends one active cycle whose resume window has elapsed at
// now and returns the cycle's current record. ExpireScanCycles skips a cycle
// whose job holds a live lease, so the scan that holds the lease uses this to
// record the expiry on its own trigger. A cycle that is still inside its
// window, or that is no longer active, is returned unchanged.
func (ss *SystemStore) ExpireScanCycle(ctx context.Context, cycleID string, now time.Time) (ScanCycleRecord, error) {
	stamp := sqliteTimestamp(now)
	result, err := ss.store.DB.ExecContext(ctx, `UPDATE scan_cycles SET status='expired',updated_at=?,finished_at=?,last_error='scan cycle exceeded its resume window' WHERE id=? AND status IN ('running','paused','stalled') AND expires_at<=?`, stamp, stamp, cycleID, stamp)
	if err != nil {
		return ScanCycleRecord{}, err
	}
	if changed, _ := result.RowsAffected(); changed == 1 {
		// The terminal state is already durable. As in StartScanCycleAttempt,
		// payload cleanup is best effort and the retention pass finishes it.
		_ = ss.clearExpiredCyclePayloads(ctx, []string{cycleID})
	}
	return ss.scanCycle(ctx, cycleID)
}

func expiredScanCycleIDs(ctx context.Context, tx *sql.Tx, stamp string) ([]string, error) {
	// A cycle with a live job lease is still being worked, even if its resume
	// window has elapsed. The scan owner renews its lease through finalization;
	// excluding it here prevents housekeeping from racing that final commit.
	rows, err := tx.QueryContext(ctx, `SELECT c.id FROM scan_cycles AS c WHERE c.status IN ('running','paused','stalled') AND c.expires_at<=? AND NOT EXISTS (SELECT 1 FROM job_leases AS l WHERE l.job=c.job_id AND l.expires_at>?) ORDER BY c.expires_at,c.id LIMIT ?`, stamp, stamp, scanCycleReconcileBatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	ids := make([]string, 0, scanCycleReconcileBatchSize)
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// clearExpiredCyclePayloads reclaims potentially large checkpoint documents
// after the terminal cycle transition. The cycle IDs are already bounded by
// ExpireScanCycles; each update is additionally limited to one batch of unit
// rows so a single broad cycle cannot monopolize the writer connection.
func (ss *SystemStore) clearExpiredCyclePayloads(ctx context.Context, ids []string) error {
	if len(ids) == 0 {
		return nil
	}
	placeholders := make([]string, len(ids))
	args := make([]any, len(ids))
	for i, id := range ids {
		placeholders[i] = "?"
		args[i] = id
	}
	args = append(args, scanCycleReconcileBatchSize)
	query := `UPDATE scan_cycle_units SET snapshot_json='{}',last_error='cycle expired' WHERE rowid IN (SELECT rowid FROM scan_cycle_units WHERE cycle_id IN (` + strings.Join(placeholders, ",") + `) AND snapshot_json<>'{}' ORDER BY rowid LIMIT ?)`
	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		result, err := ss.store.DB.ExecContext(ctx, query, args...)
		if err != nil {
			return err
		}
		count, _ := result.RowsAffected()
		if count < scanCycleReconcileBatchSize {
			return nil
		}
	}
}

// LoadScanCycleFragments returns a cycle's pinned plan and the checkpoint of
// every completed unit, in order, to merge into the cycle's scan. A reclaimed
// checkpoint is ErrMissingCheckpoint.
func (ss *SystemStore) LoadScanCycleFragments(ctx context.Context, cycleID string) (scanner.WorkPlan, []model.Snapshot, error) {
	plan, err := ss.scanCyclePlan(ctx, cycleID)
	if err != nil {
		return scanner.WorkPlan{}, nil, err
	}
	rows, err := ss.store.reader().QueryContext(ctx, `SELECT sequence,snapshot_json FROM scan_cycle_units WHERE cycle_id=? AND status='completed' ORDER BY sequence`, cycleID)
	if err != nil {
		return scanner.WorkPlan{}, nil, err
	}
	defer rows.Close()
	var fragments []model.Snapshot
	for rows.Next() {
		var sequence int
		var raw []byte
		if err = rows.Scan(&sequence, &raw); err != nil {
			return scanner.WorkPlan{}, nil, err
		}
		// '{}' is the durable sentinel used after a promoted or expired cycle's
		// large payload has been reclaimed.  Treat it as missing during recovery;
		// unmarshalling it into an empty Snapshot would otherwise look like a
		// valid zero-result fragment and could establish an empty baseline.
		trimmed := strings.TrimSpace(string(raw))
		if trimmed == "" || trimmed == "{}" || trimmed == "null" {
			return scanner.WorkPlan{}, nil, fmt.Errorf("%w: cycle %s sequence %d", ErrMissingCheckpoint, cycleID, sequence)
		}
		var snapshot model.Snapshot
		if err = json.Unmarshal(raw, &snapshot); err != nil {
			return scanner.WorkPlan{}, nil, err
		}
		fragments = append(fragments, snapshot)
	}
	return plan, fragments, rows.Err()
}

func trimCycleError(raw string) string {
	raw = strings.TrimSpace(raw)
	if len(raw) > 500 {
		return raw[:500] + "…"
	}
	return raw
}
