package store

// Schema 58 rebuilds the three resumable host-search indexes using the
// prioritized, bounded search document. Reusing the existing checkpointed
// rebuild means large installations update in small transactions and can
// resume safely after a restart. The baseline source text is regenerated by
// the backfill rather than copied from the older truncated projection.
func migration58Statements() []string {
	return []string{
		`DROP TRIGGER IF EXISTS scan_hosts_search_ai`,
		`DROP TRIGGER IF EXISTS scan_hosts_search_au`,
		`DROP TRIGGER IF EXISTS scan_hosts_search_ad`,
		`DROP TRIGGER IF EXISTS latest_scan_hosts_search_ai`,
		`DROP TRIGGER IF EXISTS latest_scan_hosts_search_au`,
		`DROP TRIGGER IF EXISTS latest_scan_hosts_search_ad`,
		`UPDATE fts_backfill_state SET last_rowid=0,processed_rows=0,initialized=0,complete=0,updated_at=datetime('now')
WHERE table_name IN ('scan_hosts','latest_scan_hosts','baseline_hosts')`,
	}
}
